type CatalogRow = readonly [string, string, string | null];

export default [
  ['eg1', 'EG 1, Alignment Color Bar Test Signal for Television Picture Monitors', null],
  [
    'rdd1',
    'RDD 1, DDRMON-MIB-1 - A Digital Disk Recorder Simple Network Management Protocol Management Information Base',
    null,
  ],
  ['st1', 'ST 1, Video Recording - 2-in Magnetic Recording Tape', null],
  ['eg2', 'EG 2, Edge Identification of Motion-Picture Raw Stock Containers', null],
  [
    'rdd2',
    'RDD 2, Use of Logarithmic Non-Linear Transfer Characteristic for Transmission of Linear Signals through Limited-Bit-Depth Image Representations and Interfaces',
    null,
  ],
  ['eg3', 'EG 3, Projection for Technical Conferences', null],
  ['rdd3', 'RDD 3, e-VTR MXF Interoperability Specification', null],
  [
    'st3',
    'ST 3, Television Analog Recording - Frequency Response and Operating Level of Recorders and Reproducers - Audio 1 Record on 2-in Tape Operating at 15 and 7.5 in/s',
    null,
  ],
  [
    'rdd4',
    'RDD 4, Pro-AV MIB-1 - A Professional Audio/Visual Product Simple Network Management Protocol Management Information Base',
    null,
  ],
  [
    'st4',
    'ST 4, Television Analog Recording - 2-in Magnetic Tape for Quadruplex Recording - Speed',
    null,
  ],
  [
    'eg5',
    'EG 5, Projected Image Quality of 70-, 35- and 16-mm Motion-Picture Projection Systems',
    null,
  ],
  ['rdd5', 'RDD 5, Film Grain Technology - Specifications for H.264 / MPEG-4 AVC Bitstreams', null],
  ['st5', 'ST 5, Television Analog Recording - 2-in Reels', null],
  [
    'rdd6',
    'RDD 6, Description and Guide to the Use of the Dolby® E Audio Metadata Serial Bitstream',
    null,
  ],
  [
    'rp6',
    'RP 6, Recorded Carrier Frequencies and Preemphasis Characteristics for 2-in Quadruplex Video Magnetic Tape Recording for 525-Line/60-Field Television Systems',
    null,
  ],
  [
    'st6',
    'ST 6, Video Recording - 2-in Quadruplex Tape - Video, Audio and Tracking-Control Records',
    null,
  ],
  [
    'eg7',
    'EG 7, Audio Sync Pulse for 8-mm Type S Cameras, Magnetic Audio Recorders and Rerecording Projectors',
    null,
  ],
  ['st7', 'ST 7, Motion-Picture Film (16-mm) - Camera Aperture Image and Usage', null],
  [
    'eg8',
    'EG 8, Specifications for Motion-Picture Camera Equipment Used in Space Environment',
    null,
  ],
  [
    'rdd8',
    'RDD 8, Storage and Distribution of Teletext Subtitles and VBI Data for High-Definition Television',
    null,
  ],
  [
    'st8',
    'ST 8, Video Recording - Quadruplex Recorders Operating at 15 in/s - Audio Level and Multifrequency Test Tape',
    null,
  ],
  [
    'eg9',
    'EG 9, Audio Recording Reference Level for Post-Production of Motion-Picture Related Materials',
    null,
  ],
  ['rdd9', 'RDD 9, MXF Interoperability Specification of Sony MPEG Long GOP Products', null],
  [
    'rp9',
    'RP 9, Dimensions of Double-Frame 35-mm 2x2 Slides for Precise Applications in Television',
    null,
  ],
  [
    'eg10',
    'EG 10, Tape Transport Geometry Parameters for 19-mm Type D-1 Television Digital Component Recording',
    null,
  ],
  [
    'rdd10',
    'RDD 10, An Open Transport and Navigational Specification, Optionally Supporting Multiple Conditional Access Systems',
    null,
  ],
  [
    'rdd11',
    'RDD 11, Bitstream Syntax and Semantics for Carriage of HDSDI Ancillary Data in an MPEG-2 Transport System',
    null,
  ],
  [
    'rp11',
    'RP 11, Tape Vacuum Guide Configuration and Position for Quadruplex Video Magnetic Tape Recording',
    null,
  ],
  [
    'st11',
    'ST 11, Video Recording - Quadruplex Recorders Operating at 7.5 in/s - Audio Level and Multifrequency Test Tape',
    null,
  ],
  ['12', '12, SMPTE Time and Control Code', null],
  ['st12-1', 'ST 12-1, Time and Control Code', '12'],
  ['st12-2', 'ST 12-2, Transmission of Time Code in the Ancillary Data Space', '12'],
  [
    'st12-3',
    'ST 12-3, Time Code for High Frame Rate Signals and Formatting in the Ancillary Data Space',
    '12',
  ],
  [
    'eg12',
    'EG 12, Control of Basic Parameters in the Manufacture of SMPTE Photographic and Magnetic Audio Test Films',
    null,
  ],
  ['rp12', 'RP 12, Screen Luminance for Drive-In Theaters', null],
  ['eg13', 'EG 13, Use of Audio Magnetic Test Films', null],
  ['eg14', 'EG 14, Acoustical Background Noise Levels in Dubbing Stages', null],
  ['rdd14', 'RDD 14, General Exchange Format-2', null],
  [
    'rp14',
    'RP 14, Plotting Data from Sensitometric Strips Exposed on Type Ib (Intensity Scale) Sensitometers',
    null,
  ],
  ['eg15', 'EG 15, Level for Analog Recording of Dialog in Motion-Picture Production', null],
  ['rdd15', 'RDD 15, Software Scripting Language for Pixel-Based Color Transformations', null],
  [
    'rp15',
    'RP 15, Calibration of Densitometers Used for Black-and-White Photographic Density Measurement',
    null,
  ],
  [
    'st15',
    'ST 15, Television Analog Recording - 1-in Type B Helical Scan - Basic System Parameters',
    null,
  ],
  [
    'eg16',
    'EG 16, Measurement Methods for Film and Digital Motion-Picture Camera Acoustical Noise — Field Method',
    null,
  ],
  [
    'rdd16',
    'RDD 16, Broadcast Cameras — Hybrid Electrical and Fiber-Optic Ball-Lock Connector Type-OPS',
    null,
  ],
  [
    'rp16',
    'RP 16, Specifications of Tracking Control Record for 2-in Quadruplex Video Magnetic Tape Recordings',
    null,
  ],
  ['st16', 'ST 16, Television Analog Recording - 1-in Type B Helical Scan - Records', null],
  [
    'eg17',
    'EG 17, B-Chain Electroacoustical Response for Preparing Magnetic Masters for Transfer to 16-mm or 35/32-mm Monaural Photographic Film',
    null,
  ],
  ['rdd17', 'RDD 17, Television —Advertising Digital Identification (Ad-ID)', null],
  [
    'rp17',
    'RP 17, Photographic Recording Technique for Measuring High-Speed Camera Image Unsteadiness',
    null,
  ],
  [
    'st17',
    'ST 17, Television Analog Recording - 1-in Type B Helical Scan - Frequency Response and Operating Level',
    null,
  ],
  ['eg18', 'EG 18, Design of Effective Cine Theaters', null],
  ['rdd18', 'RDD 18, Acquisition Metadata Sets for Video Camera Parameters', null],
  [
    'rp18',
    'RP 18, Specifications for Test Film for Subjective Checking of 16-mm Motion-Picture Audio Projectors',
    null,
  ],
  [
    'st18',
    'ST 18, Television Analog Recording - 1-in Type C - Basic System and Transport Geometry Parameters',
    null,
  ],
  [
    'rdd19',
    'RDD 19, Guidelines on the Use of Dolby® E with Video Signals at Frame Rates Greater than 30 Hz',
    null,
  ],
  ['rp19', 'RP 19, Specifications for 8-mm Type R Registration Test Film', null],
  ['st19', 'ST 19, Television Analog Recording - 1-in Type C - Records', null],
  [
    'eg20',
    'EG 20, Tape Transport Geometry Parameters for 19-mm Type D-2 Composite Format for Television Digital Recording',
    null,
  ],
  ['rdd20', 'RDD 20, Cinelink 2 Specification', null],
  ['rp20', 'RP 20, Specifications for 16-mm Registration Test Film', null],
  [
    'st20',
    'ST 20, Television Analog Recording - 1-in Type C Recorders and Reproducers - Longitudinal Audio Characteristics',
    null,
  ],
  [
    'eg21',
    'EG 21, Nomenclature for Television Digital Recording of 19-mm Type D-1 Component and Type D-2 Composite Formats',
    null,
  ],
  ['rp21', 'RP 21, Dimensions of 35-mm and 70-mm Motion-Picture Rewind Spindles', null],
  ['st21', 'ST 21, Video Recording - 3/4-in Type E Helical Scan - Records', null],
  [
    'eg22',
    'EG 22, Description and Index of Documents for 19-mm Type D-2 Composite Television Digital Recording',
    null,
  ],
  ['rdd22', 'RDD 22, Film Transfer – 2048x1556 Image Container and Signal Interface', null],
  ['st22', 'ST 22, Video Recording - 3/4-in Type E Helical Scan - Cassette', null],
  [
    'eg23',
    'EG 23, Transfer of Two-Channel Stereo Audio from Audio Magnetic Film or Tape to Video Tape',
    null,
  ],
  [
    'eg24',
    'EG 24, Video and Audio Alignment Tapes and Procedures for 1-in Type C Helical-Scan Television Analog Recorders',
    null,
  ],
  ['rdd24', 'RDD 24, Specification of the FIMS Media SOA Framework', null],
  ['rp24', 'RP 24, Dimensions for 16-mm Motion-Picture Camera', null],
  ['st24', 'ST 24, Television Recording - 1-in Reels', null],
  ['eg25', 'EG 25, Telecine Scanning for Film Transfer to Television', null],
  ['rdd25', 'RDD 25, AVC MXF Proxies', null],
  [
    'rp25',
    'RP 25, Audio and Picture Synchronization in Motion-Picture Film Relative to Leaders for Television and Theatrical Presentation for Analog Magnetic and Photographic Records',
    null,
  ],
  ['st25', 'ST 25, Video Recording - 1-in Magnetic Recording Tape', null],
  [
    'eg26',
    'EG 26, Audio Channel Assignments for Digital Television Tape Recorders with AES/EBU Digital Audio Input',
    null,
  ],
  ['rdd26', 'RDD 26, MXF OP-1b Specification for AVC with Chunk Audio', null],
  [
    'st26',
    'ST 26, Video Recording - 1-in Helical-Scan Recorders - Raw Stock for Reference Tapes',
    null,
  ],
  ['27', '27, TV Test Patterns', null],
  ['rp27-1', 'RP 27-1, Specifications for Operational Alignment Test Pattern for Television', '27'],
  [
    'rp27-2',
    'RP 27-2, Specifications for Operational Registration Test Pattern for Multiple-Channel Television Cameras',
    '27',
  ],
  [
    'rp27-3',
    'RP 27-3, Specifications for Safe Action and Safe Title Areas Test Pattern for Television Systems',
    '27',
  ],
  [
    'rp27-4',
    'RP 27-4, Specifications for an Operational Test Pattern for Checking Jitter, Weave and Travel Ghost in Television Projectors',
    '27',
  ],
  [
    'rp27-5',
    'RP 27-5, Specifications for Mid-Frequency Response Test Pattern for Television',
    '27',
  ],
  [
    'eg27',
    'EG 27, Supplemental Information for ANSI/SMPTE 170M and Background on the Development of NTSC Color Standards',
    null,
  ],
  ['eg28', 'EG 28, Annotated Glossary of Essential Terms for Electronic Production', null],
  ['rdd28', 'RDD 28, Dolby Atmos® Print Master File Specification', null],
  ['eg29', 'EG 29, Remote Control of Television Equipment', null],
  ['rdd29', 'RDD 29, Dolby Atmos® Bitstream Specification', null],
  [
    'st29',
    'ST 29, Television Analog Recording - 1-in Type B Reference Recorders - Basic System and Transport Geometry',
    null,
  ],
  ['eg30', 'EG 30, Implementation of ESlan Standards', null],
  [
    'rdd30',
    'RDD 30, ARRIRAW Image File Structure and Interpretation Supporting Deferred Demosaicing to a Logarithmic Encoding',
    null,
  ],
  [
    'st30',
    'ST 30, Television Analog Recording - 1-in Type B Reference Recorders - Records on Reference Tapes',
    null,
  ],
  ['eg31', 'EG 31, Considerations for Cassette Bar Code Readers', null],
  [
    'rdd31',
    'RDD 31, Deferred Demosaicing of an ARRIRAW Image File to a Wide-Gamut Logarithmic Encoding',
    null,
  ],
  ['st31', 'ST 31, Television Analog Recording - 3/4-in Type E - Small Video Cassette', null],
  [
    'eg32',
    'EG 32, Emphasis of AES/EBU Audio in Television Systems and Preferred Audio Sampling Rate',
    null,
  ],
  ['rdd32', 'RDD 32, XAVCTM MXF Mapping and Operating Points', null],
  [
    'rp32',
    'RP 32, Specifications for 8-mm Type S Test Film for Projectors and Printers Reel Spindles',
    null,
  ],
  ['st32', 'ST 32, Video Recording - 1/2-in Type H - Cassette, Tape and Records', null],
  ['eg33', 'EG 33, Jitter Characteristics and Measurements', null],
  ['rdd33', 'RDD 33, Format for Non-PCM Audio and Data in AES3 — Dolby-E® Data Type', null],
  ['eg34', 'EG 34, Pathological Conditions in Serial Digital Video Systems', null],
  ['rdd34', 'RDD 34, LLVC - Low Latency Video Codec for Network Transfer', null],
  ['rp34', 'RP 34, Dimensions for 16-mm Motion-Picture Projector Reel Spindles', null],
  [
    'eg35',
    'EG 35, Time and Control Code: Time Address Clock Precision for Television, Audio and Film',
    null,
  ],
  ['rdd35', 'RDD 35, TICO Lightweight Codec Used in IP Networked or in SDI Infrastructures', null],
  ['st35', 'ST 35, Television Analog Recording - 1/2-in Type G - Cassette and Tape', null],
  ['eg36', 'EG 36, Transformations Between Television Component Color Signals', null],
  ['rdd36', 'RDD 36, Apple ProRes Bitstream Syntax and Decoding Process', null],
  [
    'rp36',
    'RP 36, Positioning the Headwheel and Adjacent Tape Guides for 2-in Quadruplex Video Magnetic Tape Recorders',
    null,
  ],
  ['eg37', 'EG 37, Node Structure for the SMPTE Metadata Dictionary', null],
  ['rdd37', 'RDD 37, Uncompressed Video Transport Over MPEG-2 Transport Stream', null],
  ['st37', 'ST 37, Motion-Picture Equipment - Raw Stock Cores', null],
  ['eg38', 'EG 38, MPEG-2 Operating Range Applications', null],
  [
    'rdd38',
    'RDD 38, Networked Device Control Protocol - Message Data Structure and Method of Communication',
    null,
  ],
  ['rp38', 'RP 38, Specifications for Deflection Linearity Test Pattern for Television', null],
  ['eg39', 'EG 39, Overview of Declarative Data Essence', null],
  ['rdd39', 'RDD 39, MXF OP-1a Interoperability Specification for AVC-ULTRA', null],
  [
    'rp39',
    'RP 39, Specifications for Maintaining an Emulsion-In Orientation on Theatrical Release Prints',
    null,
  ],
  [
    'eg40',
    'EG 40, Conversion of Time Values between SMPTE ST 12-1 Time Code, MPEG-2 PCR Time Base and Absoute Time',
    null,
  ],
  ['rdd40', 'RDD 40, Essence-independent IP Live Networked Media Transport', null],
  [
    'rp40',
    'RP 40, Specifications for 35-mm Projector Alignment and Screen Image Quality Test Film',
    null,
  ],
  [
    'st40',
    'ST 40, Audio Motion-Picture Film (35-mm) - Release Prints - Photographic Analog Audio Records',
    null,
  ],
  ['eg41', 'EG 41, Material Exchange Format (MXF) - Engineering Guideline', null],
  ['rdd41', 'RDD 41, MDA D-Cinema Application', null],
  [
    'st41',
    'ST 41, Audio Motion-Picture Film (16-mm) - Prints - Photographic Analog Audio Records',
    null,
  ],
  ['eg42', 'EG 42, Material Exchange Format (MXF) - MXF Descriptive Metadata', null],
  ['rdd42', 'RDD 42, MDA Program Specification', null],
  ['eg43', 'EG 43, System Implementation of CEA-708-B and CEA-608-B Closed Captioning', null],
  ['rdd43', 'RDD 43, MDA Bitstream Specification', null],
  [
    'eg44',
    'EG 44, Care, Storage, Operation, Handling and Shipping of Magnetic Recording Tape for Television',
    null,
  ],
  ['rdd44', 'RDD 44, Material Exchange Format — Mapping and Application of Apple ProRes', null],
  ['rdd45', 'RDD 45, Interoperable Master Format – Application ProRes', null],
  ['rp45', 'RP 45, Use and Care of Sound Test Films', null],
  [
    'rdd46',
    'RDD 46, SMPTE Timecode Extensions – Relationships to Higher Rates and Date-Time',
    null,
  ],
  [
    'rdd47',
    'RDD 47, Interoperable Master Format – Isochronous Stream of XML Documents (ISXD) Plugin',
    null,
  ],
  ['rp47', 'RP 47, Electronic Method of Dropout Detection and Counting', null],
  ['rdd48', 'RDD 48, MXF Archive and Preservation Format Registered Disclosure Document', null],
  ['rp48', 'RP 48, Lubrication of 16- and 8-mm Motion-Picture Prints', null],
  [
    'st48',
    'ST 48, Motion-Picture Film (16-mm) - Picture and Sound Contact Printing - Printed Areas',
    null,
  ],
  ['rdd49', 'RDD 49, Professional Metadata (PMD) Specification', null],
  [
    'rp49',
    'RP 49, Leaders for 8-mm Type R and S Motion-Picture Release Prints Used in Continuous-Loop Cartridges',
    null,
  ],
  [
    'rdd50',
    'RDD 50, Avid DNxUncompressed – Packing definition and mapping to the MXF Generic Container',
    null,
  ],
  ['rp50', 'RP 50, Dimensions for 8-mm Type S Motion-Picture Projector Reel Spindles', null],
  ['rdd51', 'RDD 51, High Density Image Encoding for ARRIRAW Files', null],
  ['rp51', 'RP 51, Screen Luminance and Viewing Conditions for 8-mm Review Rooms', null],
  ['rdd52', 'RDD 52, D-Cinema Packaging — SMPTE DCP Bv2.1 Application Profile', null],
  [
    'rp53',
    'RP 53, Scene-Change Methods for Printing 35-mm, 16-mm and 8-mm Type S Motion-Picture Film',
    null,
  ],
  [
    'rdd54',
    'RDD 54, Material Exchange Format — Mapping ARRIRAW Bitstreams into the MXF Generic Container',
    null,
  ],
  ['rp54', 'RP 54, Edge Numbering on 16-mm Release Prints', null],
  ['rdd55', 'RDD 55, Material Exchange Format — Carriage of ARRI Camera System Metadata', null],
  ['rp55', 'RP 55, 8-mm Type S Sprocket Design', null],
  ['st55', 'ST 55, 35- and 16-mm Television Release Prints — Leaders and Cue Marks', null],
  ['rdd56', 'RDD 56, Track File for JPEG 2000 Codestreams with Time-Synchronous Metadata', null],
  ['rp56', 'RP 56, Safe Action and Safe Title Areas for 8-mm Release Prints', null],
  [
    'st56',
    'ST 56, Motion-Picture Film - Nomenclature for Studios and Processing Laboratories',
    null,
  ],
  [
    'rdd57',
    'RDD 57, SMPTE ST 2098-2 Immersive Audio Bitstream and Packaging Constraints: IAB Application Profile 1',
    null,
  ],
  ['rdd58', 'RDD 58, Carriage of Live Production Metadata', null],
  [
    'rp58',
    'RP 58, Nomenclature for Devices Enclosing 8-mm Motion-Picture Film for Projection',
    null,
  ],
  ['59', '59, Interoperable Master Format', null],
  ['rdd59-1', 'RDD 59-1, Application DPP (ProRes)', '59'],
  [
    'rp59',
    'RP 59, Color and Luminance of Review Room Screens for Viewing Motion-Picture Materials Intended for Slides or Film Strips',
    null,
  ],
  ['st59', 'ST 59, Motion-Picture Film (35-mm) - Camera Aperture Images and Usage', null],
  [
    'rdd60',
    'RDD 60, Material Exchange Format (MXF) — Mapping Immersive Audio Bitstream into the MXF Generic Container for Repository File Formats',
    null,
  ],
  [
    'rdd61',
    'RDD 61, Material Exchange Format — Mapping ARRICORE Bitstreams into the MXF Generic Container',
    null,
  ],
  [
    'rp63',
    'RP 63, Specifications for Sound-Focusing Test Film for 16-mm Audio Reproducers, Photographic Type',
    null,
  ],
  [
    'rp64',
    'RP 64, Specifications for Audio-Focusing Test Film for 35-mm Audio Reproducers, Photographic Type',
    null,
  ],
  ['rp65', 'RP 65, Motion-Picture Enlargement/Reduction Ratios', null],
  [
    'rp67',
    'RP 67, Specifications for Buzz-Track Test Film for 16-mm Motion-Picture Audio Reproducers, Photographic Type',
    null,
  ],
  [
    'rp68',
    'RP 68, Specifications for Buzz-Track Test Film for 35-mm Motion-Picture Photographic Audio Reproducers',
    null,
  ],
  [
    'rp69',
    'RP 69, Specifications for Scanning-Beam Uniformity Test Film for 35-mm Motion-Picture Audio Reproducers',
    null,
  ],
  [
    'rp70',
    'RP 70, Specifications for Flutter Test Film for 16-mm Audio Reproducers, Photographic Type',
    null,
  ],
  ['rp73', 'RP 73, 8-mm Type R (Regular 8) Sprocket Design', null],
  ['st73', 'ST 73, Motion-Picture Film (32-mm) - 35-mm Film Perforated 32-mm, 2R', null],
  ['rp74', 'RP 74, 16-mm Sprocket Design', null],
  ['st74', 'ST 74, Motion-Picture Cameras (16- and 8-mm) - Zero Point for Focusing Scales', null],
  [
    'rp75',
    'RP 75, Specifications for Flutter Test Film for 35-mm Studio Audio Reproducers, Magnetic Type',
    null,
  ],
  ['st75', 'ST 75, Motion-Picture Film - Raw Stock - Designation of A and B Windings', null],
  [
    'rp76',
    'RP 76, Specifications for Flutter Test Film for 16-mm Audio Reproducers, Magnetic Type',
    null,
  ],
  ['st76', 'ST 76, Motion-Picture Cameras - 16-mm and 8-mm Threaded Lens Mounts', null],
  [
    'rp77',
    'RP 77, Specifications for Azimuth Test Film for 35-mm Studio Audio Reproducers, Magnetic Type',
    null,
  ],
  [
    'rp78',
    'RP 78, Specifications for Azimuth Test Film for 16-mm Audio Projectors, Magnetic Type',
    null,
  ],
  [
    'rp79',
    'RP 79, Specifications for Flutter Test Film for 35-mm Four-Track Striped Release Print Audio Reproducers, Magnetic Type',
    null,
  ],
  [
    'rp81',
    'RP 81, Specifications for Scanning-Beam Uniformity Test Film for 16-mm Motion-Picture Photographic Audio Reproducers',
    null,
  ],
  [
    'rp82',
    'RP 82, Specifications for 16-mm Projector Alignment and Screen Image Quality Test Film',
    null,
  ],
  [
    'rp83',
    'RP 83, Specifications of Tracking-Control Record for 1-in Type B Helical-Scan Television Analog Recording',
    null,
  ],
  ['st83', 'ST 83, Motion -Picture Film (16-mm) - Edge Numbers - Location and Spacing', null],
  [
    'rp84',
    'RP 84, Reference Carrier Frequencies and Preemphasis Characteristics for 1-in Type B Helical-Scan Television Analog Recording',
    null,
  ],
  [
    'rp85',
    'RP 85, Tracking-Control Record for 1-in Type C Helical-Scan Television Tape Recording',
    null,
  ],
  [
    'rp86',
    'RP 86, Video Record Parameters for 1-in Type C Helical-Scan Television Tape Recording',
    null,
  ],
  [
    'st86',
    'ST 86, Motion-Picture Film - Magnetic Audio Records - Two, Three, Four and Six Records on 35-mm and One Record on 17.5-mm Magnetic Film',
    null,
  ],
  [
    'rp87',
    'RP 87, Reference Carrier Frequencies, Preemphasis Characteristic and Audio and Control Signals for 3/4-in Type E Helical-Scan Video Tape Cassette Recording',
    null,
  ],
  ['st87', 'ST 87, Motion-Picture Film (16-mm) - 100-Mil Magnetic Striping', null],
  [
    'rp90',
    'RP 90, Specifications for Type U Audio Level and Multi-frequency Test Film for 16-mm Audio Reproducers, Magnetic Type',
    null,
  ],
  [
    'rp91',
    'RP 91, Specifications for 70-mm Projector Alignment and Screen Image Quality Test Film',
    null,
  ],
  [
    'rp92',
    'RP 92, Specifications for Audio Level and Multifrequency Test Films for 8-mm Type S Audio Reproducers, Magnetic Type',
    null,
  ],
  [
    'rp93',
    'RP 93, Requirements for Recording American National Standard Time and Control Code for 1-in Type B Helical-Scan Video Tape Recorders',
    null,
  ],
  ['st93', 'ST 93, Motion-Picture Film (35-mm) - Perforated BH', null],
  ['rp94', 'RP 94, Gain Determination of Front Projection Screens', null],
  ['rp95', 'RP 95, Installation of Gain Screens', null],
  [
    'rp96',
    'RP 96, Specifications for Subjective Reference Tapes for Helical-Scan Video Tape Reproducers for Checking Receiver/Monitor Setup',
    null,
  ],
  ['st96', 'ST 96, Television - 35- and 16-mm Motion-Picture Film - Scanned Image Area', null],
  [
    'rp97',
    'RP 97, Specifications for Flutter Test Film for 35-mm Audio Reproducers, Photographic Type',
    null,
  ],
  [
    'st97',
    'ST 97, Motion-Picture Film (16-mm) - 200-Mil Edge Position - Magnetic Audio Record',
    null,
  ],
  ['rp98', 'RP 98, Measurement of Screen Luminance in Theaters', null],
  ['st101', 'ST 101, Motion-Picture Film (16-mm) - Perforated 2R-3000 - Magnetic Striping', null],
  ['st102', 'ST 102, Motion-Picture Film (35-mm) - Perforated CS-1870', null],
  [
    'rp103',
    'RP 103, Care, Storage, Operation, Handling and Shipping of Magnetic Tape for Television',
    null,
  ],
  ['rp104', 'RP 104, Cross-Modulation Tests for Variable-Area Photographic Audio Tracks', null],
  [
    'rp105',
    'RP 105, Method for Determining the Degree of Jump and Weave in 70-, 35- and 16-mm Motion-Picture Projected Images',
    null,
  ],
  [
    'rp106',
    'RP 106, Film Tension in 35-mm Motion-Picture Systems Operating Under 0.9 m/s (180 ft / min)',
    null,
  ],
  ['rp107', 'RP 107, Video and Audio Reference Tape for 1-in Type B Helical-Scan Format', null],
  [
    'rp109',
    'RP 109, Spectral Response of Photographic Audio Reproducers for 8-mm Type S Motion-Picture Film',
    null,
  ],
  ['st109', 'ST 109, Motion-Picture Film (16-mm) - Perforated 1R and 2R', null],
  [
    'rp110',
    'RP 110, Specifications for an Alignment Test Film for Anamorphic Attachments to 35-mm Motion-Picture Projectors',
    null,
  ],
  ['rp111', 'RP 111, Dimensions for 70-, 65- and 35-mm Motion-Picture Film Splices', null],
  [
    'st111',
    'ST 111, Motion-Picture Film (35-mm) - Prints Made on Continuous Contact Printers - Exposed Areas for Picture and Audio',
    null,
  ],
  ['st112', 'ST 112, Motion-Picture Film (16-mm) - 100-Mil Magnetic Audio Record', null],
  ['rp113', 'RP 113, Supervisory Protocol for Digital Control Interface', null],
  [
    'rp114',
    'RP 114, Dimensions of Photographic Control and Data Record on 16-mm Motion-Picture Film',
    null,
  ],
  [
    'rp115',
    'RP 115, Dimensions of Photographic Control and Data Record on 35-mm Motion-Picture Release Prints 15.00',
    null,
  ],
  [
    'rp116',
    'RP 116, Dimensions of Photographic Control and Data Record on 35-mm Motion-Picture Camera Negatives',
    null,
  ],
  [
    'st117',
    'ST 117, Motion-Picture Film - Photographic Audio Record - Spectral Diffuse Density',
    null,
  ],
  ['st119', 'ST 119, Motion Picture Film (70-mm) — Perforated 65-mm, KS-1870', null],
  [
    'rp120',
    'RP 120, Measurement of Intermodulation Distortion in Motion-Picture Audio Systems',
    null,
  ],
  [
    'rp121',
    'RP 121, Tape Dropout Specifications for 1-in Types B and C Video Tape Recorders / Reproducers',
    null,
  ],
  [
    'rp122',
    'RP 122, Dimensions of Cemented Splices on 8-mm Type S Motion-Picture Film, Projection Type',
    null,
  ],
  [
    'rp123',
    'RP 123, Dimensions of Tape Splices on 8-mm Type S Motion-Picture Film, Projection Type',
    null,
  ],
  [
    'rp124',
    'RP 124, Insertion Pivot for Studio Lighting Units and Mating Holders for Use with Standing and Hanging Support Systems',
    null,
  ],
  [
    'st125',
    'ST 125, SDTV Component Video Signal Coding 4:4:4 and 4:2:2 for 13.5 MHz and 18 MHz Systems',
    null,
  ],
  [
    'rp127',
    'RP 127, Specifications for Type U Audio Level and Multifrequency Analog Test Film for 35-mm Studio Audio Reproducers, Magnetic Full-Coat Type',
    null,
  ],
  [
    'st127',
    'ST 127, Motion-Picture Film (16-mm) - Magnetic-Photographic Audio Records - Magnetic Striping of Prints',
    null,
  ],
  [
    'rp128',
    'RP 128, Specifications for Audio Level and Multifrequency Test Film for 70-mm Striped Six-Track Release Print Audio Reproducers, Magnetic Type',
    null,
  ],
  [
    'rp129',
    'RP 129, Requirements for 35-, 16- and 8-mm Type S Tape Splices on Magnetic Audio Recording Motion-Picture Film',
    null,
  ],
  [
    'rp130',
    'RP 130, Dimensions of Tape Splices on 16-mm and 8-mm Type R Motion-Picture Film, Projection Type',
    null,
  ],
  ['rp131', 'RP 131, Storage of Motion-Picture Films', null],
  ['rp132', 'RP 132, Storage of Edit Decision Lists on 8-in Flexible Diskette Media', null],
  [
    'rp133',
    'RP 133, Specifications for Medical Diagnostic Imaging Test Pattern for Television Monitors and Hard-Copy Recording Cameras',
    null,
  ],
  ['rp134', 'RP 134, Polarity for Analog Audio Magnetic Recording and Reproduction', null],
  ['rp135', 'RP 135, Use of Binary User Groups in Motion-Picture Time and Control Codes', null],
  [
    'rp136',
    'RP 136, Time and Control Codes for 24, 25 or 30 Frame-Per-Second Motion-Picture Systems',
    null,
  ],
  [
    'st137',
    'ST 137, Motion-Picture Film (35-mm) - Release Prints - Four Magnetic Audio Records',
    null,
  ],
  ['rp138', 'RP 138, Control Message Architecture for Digital Control Interface', null],
  ['rp139', 'RP 139, Tributary Interconnection for Digital Control Interface', null],
  ['st139', 'ST 139, Motion-Picture Film (35-mm) - Perforated KS', null],
  [
    'rp140',
    'RP 140, Position of Analog Photographic Audio Record for Routine One-Frame Crossmodulation Test Signals',
    null,
  ],
  ['rp141', 'RP 141, Background Acoustic Noise Levels in Theaters and Review Rooms', null],
  [
    'rp142',
    'RP 142, Stereo Audio Track Allocations and Identification of Noise Reduction for Video Tape Recording',
    null,
  ],
  [
    'rp143',
    'RP 143, Specifications for Type U Audio Level and Multifrequency Test Film for 35-mm Striped Four-Track Release Print Audio Reproducers, Magnetic Type',
    null,
  ],
  [
    'st143',
    'ST 143, Motion-Picture Film (8-mm Type R) - Length of Film on Camera Spools - 25-Ft Capacity',
    null,
  ],
  [
    'rp144',
    'RP 144, Basic System and Transport Geometry Parameters for 1/2-in Type L Format',
    null,
  ],
  ['rp145', 'RP 145, SMPTE C Color Monitor Colorimetry', null],
  ['st145', 'ST 145, Motion-Picture Film (65-mm) - Perforated KS', null],
  [
    'st146',
    'ST 146, Motion-Picture Film - 16- and 8-mm Reversal Color Camera Films - Determination of Speed',
    null,
  ],
  ['rp148', 'RP 148, Relative Polarity of Stereo Audio Signals', null],
  [
    'st148',
    'ST 148, Motion-Picture Film - 35- and 16-mm Prints for Television Transmission - Film Image Area for Review Room Viewing',
    null,
  ],
  [
    'rp149',
    'RP 149, Dimensions of Transverse Cemented Splices on 16-mm and 8-mm Type R Motion-Picture Film',
    null,
  ],
  ['st149', 'ST 149, Motion-Picture Film (8-mm Type S) - Perforated 1R', null],
  [
    'rp150',
    'RP 150, Channel Assignments and Test Leader for Magnetic Film Masters Intended for Transfer to Video Media Having Stereo Audio',
    null,
  ],
  ['rp151', 'RP 151, Lubrication of 35-mm Motion-Picture Prints for Projection', null],
  [
    'st151',
    'ST 151, Motion-Picture Film (8-mm Type S) - 16-mm Film Perforated 8-mm Type S, (1-3)',
    null,
  ],
  ['rp152', 'RP 152, Edge Identification of Leader and Picture for 35-mm Release Prints', null],
  ['st152', 'ST 152, Motion-Picture Film (70-mm) - Projectable Image Area', null],
  ['rp153', 'RP 153, Method for Measuring 35- and 70-mm Shutter Efficiency', null],
  [
    'st153',
    'ST 153, Motion-Picture Film (8-mm Type S) - 16-mm Film Perforated 8-mm Type S (1-4) - Printed Areas',
    null,
  ],
  [
    'st154',
    'ST 154, Motion-Picture Film (8-mm Type S) - Projectable Image Area and Projector Usage',
    null,
  ],
  ['rp155', 'RP 155, Reference Levels for Analog and Digital Audio Systems', null],
  [
    'rp156',
    'RP 156, Bar Code Labeling for Type D-1 Component and Type D-2 Composite Cassette Identification',
    null,
  ],
  ['rp157', 'RP 157, Key and Alpha Signals', null],
  ['st157', 'ST 157, Motion-Picture Film (8-mm Type S) - Camera Aperture Image and Usage', null],
  [
    'rp158',
    'RP 158, Basic System and Transport Geometry Parameters for 1/2-in Type M-2 Format',
    null,
  ],
  ['159', '159, 8mm Type S', null],
  ['st159-1', 'ST 159-1, Cartridge-Camera Interface and Take-Up Core Drive', '159'],
  ['st159-2', 'ST 159-2, Aperture, Profile, Film Position, Pressure Pad and Flatness', '159'],
  [
    'rp160',
    'RP 160, Three-Channel Parallel Analog Component High-Definition Video Interface',
    null,
  ],
  [
    'st160',
    'ST 160, Motion-Picture Equipment (8-mm Type S) -Projection Reels - 100- to 312-mm Diameter',
    null,
  ],
  [
    'rp161',
    'RP 161, Logic Design for Decoding Digital Audio Control Words in D-1 Helical Data and Control Records',
    null,
  ],
  ['st161', 'ST 161, Motion-Picture Film (8-mm Type S) - Magnetic Striping', null],
  ['rp162', 'RP 162, Storage of Edit Decision Lists on 3-1/2 in Disks', null],
  [
    'st162',
    'ST 162, Motion-Picture Film (8-mm Type S) - 16-mm Film Perforated 8-mm Type S, (1-4) - Magnetic Striping',
    null,
  ],
  ['rp163', 'RP 163, Television - System Service Messages', null],
  [
    'st163',
    'ST 163, Motion-Picture Film (8-mm Type S) - 35-mm Film Perforated 8-mm Type S, 5R - Magnetic Striping',
    null,
  ],
  [
    'st164',
    'ST 164, Motion-Picture Film (8-mm Type S) - Magnetic Audio Record - Position, Dimensions and Reproducing Speed',
    null,
  ],
  [
    'rp165',
    'RP 165, Error Detection Checkwords and Status Flags for Use in Bit-Serial Digital Interfaces for Television',
    null,
  ],
  ['st165', 'ST 165, Motion-Picture Film (35-mm) - Perforated 8-mm Type S, 5R (1-3-5-7-0)', null],
  [
    'rp166',
    'RP 166, Critical Viewing Conditions for Evaluation of Color Television Pictures',
    null,
  ],
  [
    'st166',
    'ST 166, Motion-Picture Film (8-mm Type S) - Exposure Control and Stock Identification - Sound and Silent Camera Cartridge Notches',
    null,
  ],
  ['rp167', 'RP 167, Alignment of NTSC Color Picture Monitors', null],
  [
    'rp168',
    'RP 168, Definition of Vertical Interval Switching Point for Synchronous Video Switching',
    null,
  ],
  ['st168', 'ST 168, Motion-Picture Film (16-mm) - Perforated 8-mm Type S, (1-4)', null],
  [
    'rp169',
    'RP 169, Television, Audio and Film Time and Control Code - Auxiliary Time Address Data in Binary Groups - Dialect Specification of Directory Index Locations',
    null,
  ],
  ['st169', 'ST 169, Motion-Picture Film (35-mm) - Perforated 8-mm Type S, 2R-1664 (1-0)', null],
  [
    'rp170',
    'RP 170, Video Tape Recorder Type-Specific Messages for Digital Control Interface Annex A',
    null,
  ],
  [
    'st170',
    'ST 170, Television - Composite Analog Video Signal - NTSC for Studio Applications',
    null,
  ],
  [
    'rp171',
    'RP 171, Type-Specific Messages for Digital Control Interface of Analog Audio Tape Recorders',
    null,
  ],
  ['st171', 'ST 171, Motion-Picture Film (35-mm) - Perforated 16-mm, 3R (1-3-0)', null],
  ['rp172', 'RP 172, Common Messages for Digital Control Interface', null],
  [
    'rp173',
    'RP 173, Loudspeaker Placements for Audio Monitoring in High-Definition Electronic Production',
    null,
  ],
  [
    'st173',
    'ST 173, Motion-Picture Equipment (8-mm Type R) - Double 8-mm Camera Spools - 100-Ft Capacity',
    null,
  ],
  [
    'rp174',
    'RP 174, Bit-Parallel Digital Interface for 4:4:4:4 Component Video Signal (Single Link)',
    null,
  ],
  [
    'st174',
    'ST 174, Motion-Picture Equipment (16-mm) - Camera Spools - 50- to 400-Ft Capacity',
    null,
  ],
  ['rp175', 'RP 175, Digital Interface for 4:4:4:4 Component Video Signals (Dual Link)', null],
  ['rp176', 'RP 176, Derivation of Reference Signals for Television Camera Color Evaluation', null],
  [
    'st176',
    'ST 176, Motion-Picture Film (8-mm Type S) - 16-mm Film Perforated 2R-1667 (1-3) - Magnetic Striping',
    null,
  ],
  ['rp177', 'RP 177, Derivation of Basic Television Color Equations', null],
  [
    'st177',
    'ST 177, Motion-Picture Film (35-mm) - Four-Track Magnetic Audio Release Prints - Magnetic Striping',
    null,
  ],
  [
    'rp178',
    'RP 178, Serial Digital Interface Checkfield for 10-Bit 4:2:2 Component and 4fsc Composite Digital Signals',
    null,
  ],
  [
    'rp179',
    'RP 179, Dialect Specification of Page-Line Directory Index for Television, Audio and Film Time and Control Code for Video-Assisted Film Editing',
    null,
  ],
  [
    'st179',
    'ST 179, Motion-Picture Film (8-mm Type S) - 35-mm Film Perforated 2R (1-0) and 5R (1-3-5-7-0) - Printed Areas',
    null,
  ],
  [
    'rp180',
    'RP 180, Spectral Conditions Defining Printing Density in Motion-Picture Negative and Intermediate Films',
    null,
  ],
  [
    'rp181',
    'RP 181, Audio Sector Time Code and Equipment-Type Information for 19-mm Type D-1 Digital Component',
    null,
  ],
  [
    'st181',
    'ST 181, Motion-Picture Film (8-mm Type S) - 16-mm Film Perforated 8-mm Type S (1-3) - Printed Areas',
    null,
  ],
  ['rp182', 'RP 182, List of Virtual Machine Numbers for ESbus and ESlan Systems', null],
  ['rp183', 'RP 183, Monitoring and Diagnostics Processors', null],
  [
    'st183',
    'ST 183, Motion-Picture Film - Photographic Audio Level Test Films - Measurement of Photoelectric Output Factor',
    null,
  ],
  ['rp184', 'RP 184, Specification of Jitter in Bit-Serial Digital Systems', null],
  ['st184', 'ST 184, Motion-Picture Film - Raw Stock Identification and Labeling', null],
  ['rp185', 'RP 185, Classification of Projection Depth of Focus', null],
  [
    'st185',
    'ST 185, Motion-Picture Film (70-mm) — Six Magnetic Records on Release Prints — Position, Dimensions, Reproducing Speed and Identity',
    null,
  ],
  [
    'rp186',
    'RP 186, Video Index Information Coding for 525- and 625-Line Television Systems',
    null,
  ],
  ['rp187', 'RP 187, Center, Aspect Ratio and Blanking of Video Images', null],
  ['rp189', 'RP 189, Organization of DPX Files on TAR Tapes', null],
  ['rp190', 'RP 190, Care and Preservation of Audio Magnetic Recordings', null],
  [
    'rp191',
    'RP 191, Routing Switcher Type-Specific Messages for Remote Control of Broadcast Equipment',
    null,
  ],
  ['rp192', 'RP 192, Jitter Measurement Procedures in Bit-Serial Digital Interfaces', null],
  ['st192', 'ST 192, Motion-Picture Equipment (35-mm) - Shipping Reels for Prints', null],
  ['rp194', "RP 194, Film Negative Cutter's Conform List", null],
  [
    'st194',
    'ST 194, Motion-Picture Film (35-mm) - Projector Usage - Release Prints Having Four Perforations per Frame',
    null,
  ],
  [
    'rp195',
    'RP 195, Use of the Reference Mark in Manufacturer-Printed Latent Image Key Numbers for Unambiguous Film Frame Identification',
    null,
  ],
  [
    'st195',
    'ST 195, Motion-Picture Film (35-mm) - Motion-Picture Prints - Projectable Image Area',
    null,
  ],
  [
    'st196',
    'ST 196, Motion-Picture Film - Indoor Theater and Review Room Projection - Screen Luminance and Viewing Conditions',
    null,
  ],
  ['rp197', 'RP 197, Film-to-Video Transfer List', null],
  [
    'st197',
    'ST 197, Motion-Picture Film (8-mm Type S) - 50-Ft Model 1 Sound Camera Cartridge - Cartridge, Cartridge-Camera Interface and Take-Up Core',
    null,
  ],
  ['rp198', 'RP 198, Bit-Serial Digital Checkfield for Use in High-Definition Interfaces', null],
  [
    'st198',
    'ST 198, Motion-Picture Film (8-mm Type S) - 50-Ft Model 1 Sound Camera Cartridge - Aperture, Pressure Pad and Film Position',
    null,
  ],
  [
    'rp199',
    'RP 199, Mapping of Pictures in Wide-Screen (16:9) Scanning Structure to Retain Original Aspect Ratio of the Work',
    null,
  ],
  [
    'st199',
    'ST 199, Motion-Picture Film (8-mm Type S) - 50-Ft Model 1 Sound Camera Cartridge - Pressure Pad Flatness and Camera Aperture Profile',
    null,
  ],
  [
    'rp200',
    'RP 200, Relative and Absolute Sound Pressure Levels for Motion-Picture Multichannel Sound Systems – Applicable for Analog Photographic Film Audio, Digital Photographic Film Audio and D-Cinema',
    null,
  ],
  [
    'st200',
    'ST 200, Motion-Picture Equipment (8-mm Type S) - Model 1 Camera Cartridge - Camera Run Length, Perforation Cutout and End-of-Run Notch',
    null,
  ],
  ['rp201', 'RP 201, Encoding Film Transfer Information Using Vertical Interval Time Code', null],
  ['st201', 'ST 201, Motion-Picture Film (16-mm) - Type W Camera Aperture Image', null],
  ['rp202', 'RP 202, Video Alignment for Compression Coding', null],
  [
    'st202',
    'ST 202, Motion-Pictures - Dubbing Theaters, Review Rooms and Indoor Theaters - B-Chain Electroacoustic Response',
    null,
  ],
  [
    'rp203',
    'RP 203, Real-Time Opportunistic Data Flow Control in an MPEG-2 Transport Emission Multiplex',
    null,
  ],
  [
    'st203',
    'ST 203, Motion-Picture Film (35-mm) — Prints — Two-Track Photographic Analog Audio Records',
    null,
  ],
  ['rp204', 'RP 204, SDTI-CP MPEG Decoder Templates', null],
  [
    'rp205',
    'RP 205, Application of Unique Material Identifiers in Production and Broadcast Environments',
    null,
  ],
  [
    'st205',
    'ST 205, Motion-Picture Equipment (8-mm Type S) - Model 1 Camera Cartridge - Interface and Take-Up Core Drive (200-Ft Capacity)',
    null,
  ],
  [
    'rp206',
    'RP 206, Opportunistic Data Flow Control Using Ethernet as a Control Channel in an MPEG-2 Transport Emissions Multiplex',
    null,
  ],
  [
    'st206',
    'ST 206, Motion-Picture Equipment (8-mm Type S) - Model 1 Sound Camera Cartridge - Aperture, Profile, Film Position, Pressure Pad and Flatness (200-Ft Capacity)',
    null,
  ],
  ['rp207', 'RP 207, Transport of Program Description Data in Ancillary Data Packets', null],
  [
    'st207',
    'ST 207, Television - Digital Control Interface - Electrical and Mechanical Characteristics',
    null,
  ],
  ['rp208', 'RP 208, Transport of VBI Packet Data in Ancillary Data Packets', null],
  [
    'st208',
    'ST 208, Motion-Picture Film - 35- and 16-mm Magnetic Audio Records - Recorded Characteristics',
    null,
  ],
  [
    'rp209',
    'RP 209, Format for Transmission of HD-D5 Compressed Video and Audio Data over 360 Mb/s Serial Digital Interface',
    null,
  ],
  [
    'st209',
    'ST 209, Motion-Picture Film (8-mm Type S) - Magnetic Audio Records - Recorded Characteristic',
    null,
  ],
  ['rp210', 'RP 210, Metadata Element Dictionary', null],
  [
    'st210',
    'ST 210, Motion-Picture Film (16-mm) - Magnetic Audio Records - Two Records on 16-mm Magnetic Film',
    null,
  ],
  [
    'rp211',
    'RP 211, Implementation of 24P, 25P and 30P Segmented Frames for 1920 x 1080 Production Format',
    null,
  ],
  [
    'st211',
    'ST 211, Motion-Picture Film - 16- and 35-mm Variable-Area Photographic Audio Records - Signal-to-Noise Ratio',
    null,
  ],
  [
    'rp212',
    'RP 212, Ancillary Data Mapping over MPEG-2 Video Elementary Stream Editing Information',
    null,
  ],
  [
    'st212',
    'ST 212, Motion-Picture Equipment (8-mm Type S) - Projection Reels - 75-mm Diameter',
    null,
  ],
  ['rp213', 'RP 213, MPEG-2 Operating Ranges', null],
  [
    'rp214',
    'RP 214, Packing KLV Encoded Metadata and Data Essence into SMPTE 291M Ancillary Data Packets',
    null,
  ],
  [
    'st214',
    'ST 214, Motion-Picture Film (35-mm) - Analog Photographic Audio Reproduction Characteristics',
    null,
  ],
  [
    'rp215',
    'RP 215, Vertical Ancillary Data Mapping of Film Transfer and Video Production Information',
    null,
  ],
  ['st215', 'ST 215, Motion-Picture Film (65-mm) - Camera Aperture Image', null],
  [
    'rp216',
    'RP 216, Specifications for 3-Perforation Test and Alignment Film for 35-mm Motion Pictures',
    null,
  ],
  [
    'st216',
    'ST 216, Motion-Picture Film (35-mm) - Four-Track Striped Release Prints - Recorded Characteristic of Magnetic Audio Records',
    null,
  ],
  ['rp217', 'RP 217, Nonsynchronized Mapping of KLV Packets into MPEG-2 Systems Streams', null],
  [
    'st217',
    'ST 217, Motion-Picture Film (70-mm) — Striped Release Prints — Recorded Characteristics of Magnetic Audio Records',
    null,
  ],
  [
    'rp218',
    'RP 218, Specifications for Safe Action and Safe Title Areas for Television Systems',
    null,
  ],
  [
    'st218',
    'ST 218, Motion-Picture Film (16-mm) - 200-Mil Center-Position Magnetic Audio Record',
    null,
  ],
  ['219', '219, Color Bar Signals', null],
  ['rp219-1', 'RP 219-1, High-Definition, Standard-Definition Compatible Color Bar Signal', '219'],
  [
    'rp219-2',
    'RP 219-2, Ultra High-Definition, 2048 x 1080 and 4096 x 2160 Compatible Color Bar Signal',
    '219',
  ],
  ['rp219', 'RP 219, High-Definition, Standard-Definition Compatible Color Bar Signal', null],
  ['rp220', 'RP 220, PAL/SECAM IP and Trigger Binding to VBI', null],
  [
    'st220',
    'ST 220, Motion-Picture and Television Equipment - Camera Mounting Connections - 1/4-Inch-20 Thread and 3/8-Inch-16 Thread Tripod Screws',
    null,
  ],
  [
    'rp221',
    'RP 221, Specifications for Extraction of 4x3 Areas from Digital 16x9 Images for Television Systems',
    null,
  ],
  [
    'st221',
    'ST 221, Audio Motion-Picture Film (70-mm) - Six-Track Audio Release Prints - Magnetic Striping Dimensions',
    null,
  ],
  ['rp222', 'RP 222, Standard Definition Evaluation Masters for Digital Television', null],
  [
    'st222',
    'ST 222, Television - Control and Review Rooms - Monitor System Electroacoustic Response',
    null,
  ],
  [
    'rp223',
    'RP 223, Packing UMID and Program Identification Label Data into SMPTE 291M Ancillary Data Packets',
    null,
  ],
  ['st223', 'ST 223, Motion-Picture Film - Safety Film', null],
  ['rp224', 'RP 224, SMPTE Labels Register', null],
  ['st224', 'ST 224, Television Digital Component Recording - 19-mm Type D-1 - Tape Record', null],
  ['rp225', 'RP 225, Registered Private Information in KLV', null],
  [
    'st225',
    'ST 225, Television Digital Component Recording - 19-mm Type D-1 - Magnetic Tape',
    null,
  ],
  ['st226', 'ST 226, Television Digital Recording - 19-mm Tape Cassettes', null],
  ['rp227', 'RP 227, VC-1 Bitstream Transport Encodings', null],
  [
    'st227',
    'ST 227, Television Digital Component Recording - 19-mm Type D-1 - Helical Data and Control Records',
    null,
  ],
  ['rp228', 'RP 228, VC-1 Decoder and Bitstream Conformance', null],
  [
    'st228',
    'ST 228, Television Digital Component Recording - 19-mm Type D-1 - Time and Control Code and Cue Records',
    null,
  ],
  ['st229', 'ST 229, Television Analog Recording - 1/2-in Type L - Records', null],
  [
    'st230',
    'ST 230, Television Analog Recording - 1/2-in Type L - Electrical Parameters, Control Code and Tracking Control',
    null,
  ],
  ['st231', 'ST 231, Motion-Picture Film (8-mm Type R) - Camera Aperture Image and Usage', null],
  [
    'st233',
    'ST 233, Motion-Picture Film (16-mm, does not include Super 16) - Projectable Image Area and Projector Usage',
    null,
  ],
  [
    'st234',
    'ST 234, Motion-Picture Film (8-mm Type R) - Projectable Image Area and Projector Usage',
    null,
  ],
  [
    'st235',
    'ST 235, Motion-Picture Equipment (16-mm) - Projection Reels - 200- to 2300-Ft Capacity',
    null,
  ],
  ['st236', 'ST 236, Motion-Picture Equipment (8-mm Type R) - Projection Reels', null],
  ['st237', 'ST 237, Motion-Picture Film (35-mm) - Perforated DH-1870', null],
  ['st238', 'ST 238, Television Analog Recording - 1/2-in Type L - Tapes and Cassettes', null],
  ['st239', 'ST 239, Motion-Picture Film (16-mm) - Perforated 8-mm Type R, 2R', null],
  [
    'st240',
    'ST 240, Television - 1125-Line High-Definition Production Systems - Signal Parameters',
    null,
  ],
  ['st241', 'ST 241, Motion-Picture Equipment — 35-mm and 70-mm Projection Reels', null],
  ['st242', 'ST 242, Motion-Picture Equipment (35-mm) - Universal Intermittent Sprockets', null],
  ['st243', 'ST 243, Motion-Picture Equipment - 35- and 70-mm Projection Lenses and Mounts', null],
  [
    'st244',
    'ST 244, Television - System M/NTSC Composite Video Signals - Bit-Parallel Digital Interface',
    null,
  ],
  [
    'st245',
    'ST 245, Television Digital Recording - 19-mm Type D-2 Composite Format - Tape Record',
    null,
  ],
  [
    'st246',
    'ST 246, Television Digital Recording - 19-mm Type D-2 Composite Format - Magnetic Tape',
    null,
  ],
  [
    'st247',
    'ST 247, Television Digital Recording - 19-mm Type D-2 Composite Format - Helical Data and Control Records',
    null,
  ],
  [
    'st248',
    'ST 248, Television Digital Recording - 19-mm Type D-2 Composite Format - Cue Record and Time and Control Code Record',
    null,
  ],
  ['st249', 'ST 249, Television Analog Recording - 1/2-in Type M-2 - Records', null],
  ['st250', 'ST 250, Television Analog Recording - 1/2-in Type M-2 - Tapes and Cassettes', null],
  [
    'st251',
    'ST 251, Television Analog Recording - 1/2-in Type M-2 - Electrical Parameters of Video, Audio, Time and Control Code and Tracking Control',
    null,
  ],
  [
    'st252',
    'ST 252, Television Analog Recording - 1/2-in Type M-2 - Pulse Code Modulation Audio',
    null,
  ],
  ['st253', 'ST 253, Television - Three-Channel RGB Analog Video Interface', null],
  [
    'st254',
    'ST 254, Motion-Picture Film (35-mm) - Manufacturer-Printed, Latent Image Identification Information',
    null,
  ],
  ['st256', 'ST 256, Television - Specifications for Video Tape Leader', null],
  [
    'st257',
    'ST 257, Motion-Picture Film (35-mm) - Stereoscopic Prints with Vertically Positioned Subframes - Projectable Image Areas',
    null,
  ],
  ['st258', 'ST 258, Television - Transfer of Edit Decision Lists', null],
  ['st259', 'ST 259, Television - SDTV Digital Signal/Data - Serial Digital Interface', null],
  [
    'st260',
    'ST 260, Television - 1125/60 High-Definition Production System - Digital Representation and Bit-Parallel Interface',
    null,
  ],
  [
    'st262',
    'ST 262, Television, Audio and Film - Binary Groups of Time and Control Codes - Storage and Transmission of Data',
    null,
  ],
  [
    'st263',
    'ST 263, Television Digital Recording - 1/2-in Type D-3 Composite and Type D-5 Component Format - Tape Cassette',
    null,
  ],
  [
    'st264',
    'ST 264, Television Digital Recording - 1/2-in Type D-3 Composite Format - 525/60',
    null,
  ],
  [
    'st265',
    'ST 265, Television Digital Recording - 1/2-in Type D-3 Composite Format - 625/50',
    null,
  ],
  ['st266', 'ST 266, SD Digital Component Systems – Digital Vertical Interval Time Code', null],
  [
    'st267',
    'ST 267, Television - Bit-Parallel Digital Interface - Component Video Signal 4:2:2 16x9 Aspect Ratio',
    null,
  ],
  ['268', '268, Digital Moving-Picture Exchange (DPX)', null],
  ['st268-1', 'ST 268-1, File Format for Digital Moving-Picture Exchange (DPX)', '268'],
  ['st268-2', 'ST 268-2, Format Extensions for High Dynamic Range and Wide Color Gamut', '268'],
  ['rp268-3', 'RP 268-3, Reference Materials for DPX V2.0 HDR Implementations', '268'],
  ['st268', 'ST 268, File Format for Digital Moving- Picture Exchange (DPX)', null],
  ['st269', 'ST 269, Television - Fault Reporting in Television Systems', null],
  [
    'st270',
    'ST 270, Motion-Picture Film (65-mm) - Manufacturer-Printed Latent Image Identification Information',
    null,
  ],
  [
    'st271',
    'ST 271, Motion-Picture Film (16-mm) - Manufacturer-Printed Latent Image Identification Information',
    null,
  ],
  [
    'st272',
    'ST 272, Television - Formatting AES/EBU Audio and Auxiliary Data into Digital Video Ancillary Data Space',
    null,
  ],
  ['st273', 'ST 273, Television - Status Monitoring and Diagnostics Protocol', null],
  [
    'st274',
    'ST 274, Television - 1920 x 1080 Image Sample Structure, Digital Representation and Digital Timing Reference Sequences for Multiple Picture Rates',
    null,
  ],
  ['st275', 'ST 275, Television and Audio Equipment - ESlan-1 Remote Control System', null],
  [
    'st276',
    'ST 276, Television - Transmission of AES-EBU Digital Audio Signals Over Coaxial Cable',
    null,
  ],
  [
    'st277',
    'ST 277, Television Digital Recording - 19-mm Type D-6 - Helical Data, Longitudinal Index, Cue and Control Records',
    null,
  ],
  [
    'st278',
    'ST 278, Television Digital Recording - 19-mm Type D-6 - Content of Helical Data and Time and Control Code Records',
    null,
  ],
  [
    'st279',
    'ST 279, Digital Video Recording - 1/2-in Type D-5 Standard-Definition Component Video and Type HD-D5 High-Definition Video Compressed Data',
    null,
  ],
  ['291', '291, Ancillary Data', null],
  ['st291-1', 'ST 291-1, Ancillary Data Packet and Space Formatting', '291'],
  [
    'rp291-2',
    'RP 291-2, 4:2:2 SDTV and HDTV Component Systems and 4:2:2 2048 ×1080 Production Image Formats',
    '291',
  ],
  ['rp291', 'RP 291, Assigned Ancillary Identification Codes', null],
  ['st291', 'ST 291, Television - Ancillary Data Packet and Space Formatting', null],
  ['292', '292, Serial Digital Interface 1.5 Gb/s', null],
  ['ov292-0', 'OV 292-0, Roadmap for the 292 Document Suite', '292'],
  ['st292-1', 'ST 292-1, 1.5 Gb/s Signal/Data Serial Interface', '292'],
  [
    'st292-2',
    'ST 292-2, Dual 1.5 Gb/s Serial Digital Interface for Stereoscopic Image Transport',
    '292',
  ],
  [
    'st293',
    'ST 293, Television - 720 x 483 Active Line at 59.94-Hz Progressive Scan Production - Digital Representation',
    null,
  ],
  [
    'st294',
    'ST 294, Television - 720 x 483 Active Line at 59.94-Hz Progressive Scan Production - Bit-Serial Interfaces',
    null,
  ],
  ['st295', 'ST 295, Television - 1920 x 1080 50-Hz - Scanning and Interface', null],
  [
    'st296',
    'ST 296, 1280 x 720 Progressive Image 4:2:2 and 4:4:4 Sample Structure – Analog and Digital Representation and Analog Interface',
    null,
  ],
  ['297', '297, Multi-Link and Multi-Channel 1.5G, 3G, 6G and 12G-SDI', null],
  ['ov297-0', 'OV 297-0, Overview for the 297 Document Suite', '297'],
  [
    'st297-1',
    'ST 297-1, Serial Digital Fiber Transmission System for SMPTE ST 259, ST 344, ST 292-1/2, ST 424, ST 2081-1 and ST 2082-1 Signals',
    '297',
  ],
  ['st297-2', 'ST 297-2, Multi-Link and Multi-Channel 1.5G, 3G, 6G and 12G-SDI Using CWDM', '297'],
  [
    'st297',
    'ST 297, Serial Digital Fiber Transmission System for SMPTE ST 259, SMPTE ST 344, SMPTE ST 292-1/2, SMPTE ST 424, SMPTE ST 2081-1 and SMPTE ST 2082-1 Signals',
    null,
  ],
  [
    'st298',
    'ST 298, Television - Universal Labels for Unique Identification of Digital Data',
    null,
  ],
  ['299', '299, 24-Bit Digital Audio Format', null],
  [
    'ov299-0',
    'OV 299-0, 24-Bit Digital Audio Format forSMPTE 292 Bit-Serial Interface —Roadmap for the 299 Document Suite',
    '299',
  ],
  ['st299-1', 'ST 299-1, 24-Bit Digital Audio Format for SMPTE 292M Bit-Serial Interface', '299'],
  [
    'st299-2',
    'ST 299-2, Extension of the 24-Bit Digital Audio Format to 32 Channels for 3 Gb/s Bit-Serial Interfaces',
    '299',
  ],
  [
    'st300',
    'ST 300, Motion-Picture Color Print Film (35-mm) - Manufacturer-Printed Latent Image Identification Information',
    null,
  ],
  ['st301', 'ST 301, Motion-Picture Film - Theater Projection Leader, Trailer and Cue Marks', null],
  ['st302', 'ST 302, Television - Mapping of AES3 Data into MPEG-2 Transport Stream', null],
  ['st303', 'ST 303, Television - Color Reference Pattern', null],
  [
    'st304',
    'ST 304, Television - Broadcast Cameras - Hybrid Electrical and Fiber-Optic Connector',
    null,
  ],
  ['st305', 'ST 305, Television - Serial Data Transport Interface (SDTI)', null],
  [
    'st306',
    'ST 306, Television Digital Recording - 6.35-mm Type D-7 Component Format - Video Compression at 25 Mb/s - 525/60 and 625/50',
    null,
  ],
  [
    'st307',
    'ST 307, Television Digital Recording - 6.35-mm Type D-7 Component Format - Tape Cassette',
    null,
  ],
  ['st308', 'ST 308, Television - MPEG-2 4:2:2 Profile at High Level', null],
  [
    'st309',
    'ST 309, Transmission of Date and Time Zone Information in Binary Groups of Time and Control Code',
    null,
  ],
  [
    'st310',
    'ST 310, Television - Synchronous Serial Interface for MPEG-2 Digital Transport Streams',
    null,
  ],
  ['st311', 'ST 311, Television - Hybrid Electrical and Fiber Optical Camera Cable', null],
  ['st312', 'ST 312, Television - Splice Points for MPEG-2 Transport Streams', null],
  [
    'st313',
    'ST 313, Motion-Picture Film (65-mm) - Manufacturer-Printed Latent Image Identification Information - 120 Perforation Repeat',
    null,
  ],
  [
    'st314',
    'ST 314, Television - Data Structure for DV-Based Audio, Data and Compressed Video - 25 and 50 Mb/s',
    null,
  ],
  [
    'st315',
    'ST 315, Television - Camera Positioning Information Conveyed by Ancillary Data Packets',
    null,
  ],
  [
    'st316',
    'ST 316, Television Digital Recording - 12.65-mm Type D-9 Component Format - Video Compression - 525/60 and 625/50',
    null,
  ],
  [
    'st317',
    'ST 317, Television Digital Recording - 12.65-mm Type D-9 Component Format - Tape Cassette',
    null,
  ],
  [
    'st318',
    'ST 318, Synchronization of 59.94- or 50-Hz Related Video and Audio Systems in Analog and Digital Areas — Reference Signals',
    null,
  ],
  [
    'st319',
    'ST 319, Television - Transporting MPEG-2 Recoding Information through 4:2:2 Component Digital Interfaces',
    null,
  ],
  [
    'st321',
    'ST 321, Television - Data Stream Format for the Exchange of DV-Based Audio, Data and Compressed Video Over a Serial Data Transport Interface',
    null,
  ],
  [
    'st322',
    'ST 322, Television - Format for Transmission of DV Compressed Video, Audio and Data Over a Serial Data Transport Interface',
    null,
  ],
  [
    'st323',
    'ST 323, Motion-Picture Film - Channel Assignments and Levels on Multichannel 5.1 Audio Media',
    null,
  ],
  ['st324', 'ST 324, Television - Serial Interface for Multiplexing Eight AES Data Streams', null],
  ['st325', 'ST 325, Digital Television - Opportunistic Data Broadcast Flow Control', null],
  ['st326', 'ST 326, Television - SDTI Content Package Format (SDTI-CP)', null],
  ['st327', 'ST 327, Television - MPEG-2 Video Recoding Data Set', null],
  ['st328', 'ST 328, Television - MPEG-2 Video Elementary Stream Editing Information', null],
  ['st329', 'ST 329, Television - MPEG-2 Video Recoding Data Set - Compressed Stream Format', null],
  ['st330', 'ST 330, Unique Material Identifier (UMID)', null],
  ['st331', 'ST 331, Element and Metadata Definitions for the SDTI-CP', null],
  ['st332', 'ST 332, Television - Encapsulation of Data Packet Streams Over SDTI (SDTI-PF)', null],
  ['st333', 'ST 333, Television - DTV Closed-Caption Server to Encoder Interface', null],
  ['334', '334, Caption', null],
  [
    'st334-1',
    'ST 334-1, Vertical Ancillary Data Mapping of Caption Data and Other Related Data',
    '334',
  ],
  ['st334-2', 'ST 334-2, Caption Distribution Packet (CDP) Definition', '334'],
  ['st335', 'ST 335, Metadata Element Dictionary Structure', null],
  ['st336', 'ST 336, Data Encoding Protocol using Key-Length-Value', null],
  [
    'st337',
    'ST 337, Format for Non-PCM Audio and Data in an AES3 Serial Digital Audio Interface',
    null,
  ],
  ['st338', 'ST 338, Format for Non-PCM Audio and Data in AES3 - Data Types', null],
  ['st339', 'ST 339, Format for Non-PCM Audio and Data in AES3 — Generic Data Types', null],
  [
    'st340',
    'ST 340, Format for Non-PCM Audio and Data in AES3 — ATSC A/52 Digital Audio Compression Standard for AC-3 and Enhanced AC-3 Data Types',
    null,
  ],
  [
    'st341',
    'ST 341, Television - Format for Non-PCM Audio and Data in AES3 - Captioning Data Type',
    null,
  ],
  [
    'st342',
    'ST 342, Television - HD-D5 Compressed Video 1080i and 720p Systems - Encoding Process and Data Format',
    null,
  ],
  [
    'st343',
    'ST 343, Television - Declarative Data Essence - Local Identifier (lid:) URI Scheme',
    null,
  ],
  ['st344', 'ST 344, Television - 540 Mb/s Serial Digital Interface', null],
  [
    'st345',
    'ST 345, Television - Mapping of SYNC Stream Block in ATM Common Layer to ATM Adaption Layer Type 1',
    null,
  ],
  [
    'st346',
    'ST 346, Television - Time Division Multiplexing Video Signals and Generic Data over High-Definition Television Interfaces',
    null,
  ],
  [
    'st347',
    'ST 347, Television - 540 Mb/s Serial Digital Interface - Source Image Format Mapping',
    null,
  ],
  ['st348', 'ST 348, Television - High Data Rate Serial Data Transport Interface (HD-SDTI)', null],
  [
    'st349',
    'ST 349, Television - Transport of Alternate Source Image Formats through SMPTE 292M',
    null,
  ],
  [
    'st351',
    'ST 351, Television - Transporting MPEG-2 Recoding Information through High-Definition Digital Interfaces',
    null,
  ],
  ['st352', 'ST 352, Payload Identification Codes For Serial Digital Interfaces', null],
  [
    'st353',
    'ST 353, Television - Transport of MPEG-2 Recoding Information as Ancillary Data Packets',
    null,
  ],
  [
    'st354',
    'ST 354, Television - ATM Common Layer for Transport of Packetized Audio, Video and Data over Asychronous Transfer Mode using ATM Adaption Layer Type 1',
    null,
  ],
  ['st355', 'ST 355, Television - Format for Non-PCM Audio and Data in AES - KLV Data Type', null],
  [
    'st356',
    'ST 356, Television - Type D-10 Stream Specifica-tions - MPEG-2 4:2:2P @ ML for 525/60 and 625/50',
    null,
  ],
  [
    'st357',
    'ST 357, Television - Declarative Data Essence - Internet Protocol Multicast Encapsulation',
    null,
  ],
  ['st358', 'ST 358, Television - Four-Circuit Fiber Optic Connector', null],
  ['st359', 'ST 359, Television and Motion-Pictures - Dynamic Documents', null],
  ['st360', 'ST 360, General Exchange Format', null],
  ['st361', 'ST 361, Television - NTSC IP and Trigger Binding to VBI', null],
  [
    'st362',
    'ST 362, Television - Object Data Format for the Exchange of DV-Based Audio, Data and Compressed Video using ATM Common Layer over Asychronous Transfer Mode, AAL Type 1',
    null,
  ],
  ['363', '363, Declarative Data Essence', null],
  ['st363-2', 'ST 363-2, Content Level 1', '363'],
  [
    'st364',
    'ST 364, Television - Declarative Data Essence - Unidirectional Hypertext Transport Protocol',
    null,
  ],
  [
    'st365',
    'ST 365, Digital Television Tape Recording - 12.65-mm Type D-10 Format for MPEG-2 Compressed Video - 525/60 and 625/50',
    null,
  ],
  [
    'st366',
    'ST 366, Television - Declarative Data Essence - Document Object Model Level 0 (DOM-0) and Related Object Environment',
    null,
  ],
  ['st367', 'ST 367, Television - Type D-11 Picture Compression and Data Stream Format', null],
  ['st368', 'ST 368, Digital Television Tape Recording - 12.65-mm Type D-11 Format', null],
  ['st369', 'ST 369, Television - Type D-11 Data Stream and AES3 Data Mapping over SDTI', null],
  [
    'st370',
    'ST 370, Data Structure for DV-Based Audio, Data and Compressed Video at 100 Mb/s 1080/60i, 1080/50i, 720/60p, 720/50p',
    null,
  ],
  [
    'st371',
    'ST 371, Television - 6.35-mm Type D-12 Component Format - Digital Recording at 100 Mb/s 1080/60i, 1080/50i, 720/60p',
    null,
  ],
  [
    'st372',
    'ST 372, Dual Link 1.5 Gb/s Digital Interface for 1920 × 1080 and 2048 × 1080 Picture Formats',
    null,
  ],
  [
    'st374',
    'ST 374, Television - Mapping of Vertical Ancillary Data Packets and Extended Video Line Data into Video DIF Blocks of DV-Based 50 Mb/s DIF Stream Format',
    null,
  ],
  [
    'st375',
    'ST 375, Television - Mapping of Vertical Ancillary Data Packets (VANC) into VAUX DIF Blocks of DV-Based 100 Mb/s DIF Stream Format',
    null,
  ],
  [
    'st376',
    'ST 376, Television - Mapping of Vertical Ancillary Data Packets (VANC) into VAUX DIF Blocks of DV-Based 25 Mb/s or 50 Mb/s Streams and Extended Video Line Data into VAUX DIF Blocks of DV-Based 25 Mb/s DIF Stream',
    null,
  ],
  ['377', '377, Material Exchange Format (MXF)', null],
  ['st377-1', 'ST 377-1, File Format Specification', '377'],
  ['st377-2', 'ST 377-2, MXF KLV-Encoded Extension Syntax (KXS)', '377'],
  [
    'eg377-3',
    'EG 377-3, Material Exchange Format (MXF) —Engineering Guideline (Informative)',
    '377',
  ],
  ['st377-4', 'ST 377-4, MXF Multichannel Audio Labeling Framework', '377'],
  [
    'st377-41',
    'ST 377-41, MXF Multichannel Audio Controlled Vocabulary: Content Property Values',
    '377',
  ],
  ['st377-42', 'ST 377-42, MCA Label Controlled Vocabulary', '377'],
  ['st377', 'ST 377, Material Exchange Format (MXF) — File Format Specification', null],
  [
    'st378',
    'ST 378, Material Exchange Format (MXF) - Operational Pattern 1a (Single Item, Single Package)',
    null,
  ],
  ['379', '379, MXF Generic Container', null],
  ['ov379-0', 'OV 379-0, Overview for the SMPTE ST 379 Document Suite', '379'],
  ['st379-1', 'ST 379-1, MXF Generic Container', '379'],
  ['st379-2', 'ST 379-2, Material Exchange Format (MXF) —MXF Constrained Generic Container', '379'],
  ['st379', 'ST 379, Material Exchange Format (MXF) — MXF Generic Container', null],
  [
    'st380',
    'ST 380, Material Exchange Format (MXF) - Descriptive Metadata Scheme-1 (Standard, Dynamic)',
    null,
  ],
  ['381', '381, MXF Mapping Streams into Generic Container', null],
  ['st381-1', 'ST 381-1, Mapping MPEG Streams into the MXF Generic Container', '381'],
  ['st381-2', 'ST 381-2, Mapping MPEG Streams into the MXF Constrained Generic Container', '381'],
  [
    'st381-3',
    'ST 381-3, Material Exchange Format— Mapping AVC Streams into the MXF Generic Container',
    '381',
  ],
  ['st381-4', 'ST 381-4, Mapping AAC Compresed Audio into the MXF Generic Container', '381'],
  ['st381-5', 'ST 381-5, Mapping HEVC Streams into the MXF Generic Container', '381'],
  [
    'st381',
    'ST 381, Material Exchange Format (MXF) - Mapping MPEG Streams into the MXF Generic Container (Dynamic)',
    null,
  ],
  [
    'st382',
    'ST 382, Material Exchange Format — Mapping AES3 and Broadcast Wave Audio into the MXF Generic Container',
    null,
  ],
  [
    'st383',
    'ST 383, Material Exchange Format (MXF) - Mapping DV-DIF Data to the MXF Generic Container',
    null,
  ],
  [
    'st384',
    'ST 384, Television - Material Exchange Format (MXF) - Mapping of Uncompressed Pictures into the Generic Container',
    null,
  ],
  [
    'st385',
    'ST 385, Material Exchange Format (MXF) – Mapping SDTI-CP Essence and Metadata into the MXF Generic Container',
    null,
  ],
  [
    'st386',
    'ST 386, Material Exchange Format (MXF) - Mapping Type D-10 Essence Data to the MXF Generic Container',
    null,
  ],
  [
    'st387',
    'ST 387, Material Exchange Format (MXF) - Mapping Type D-11 Essence Data to the MXF Generic Container',
    null,
  ],
  [
    'st388',
    'ST 388, Material Exchange Format (MXF) - Mapping A-law Coded Audio into the MXF Generic Container',
    null,
  ],
  [
    'st389',
    'ST 389, Material Exchange Format (MXF) - MXF Generic Container Reverse Play System Element',
    null,
  ],
  [
    'st390',
    'ST 390, Material Exchange Format (MXF) — Specialized Operational Pattern “OP-Atom” (Simplified Representation of a Single Item)',
    null,
  ],
  [
    'st391',
    'ST 391, Material Exchange Format (MXF) - Operational Pattern 1b (Single Item, Ganged Packages)',
    null,
  ],
  [
    'st392',
    'ST 392, Material Exchange Format (MXF) — Operational Pattern 2a (Play-List Items, Single Package)',
    null,
  ],
  [
    'st393',
    'ST 393, Material Exchange Format (MXF) - Operational Pattern 2b (Play-List Items, Ganged Packages)',
    null,
  ],
  [
    'st394',
    'ST 394, Material Exchange Format (MXF) - System Scheme 1 for the MXF Generic Container',
    null,
  ],
  ['st395', 'ST 395, Metadata Groups Register', null],
  [
    'st396',
    'ST 396, Television - Packet Format and Transmission Timing of DV-Based Data Streams over IEEE 1394',
    null,
  ],
  ['st397', 'ST 397, Declarative Data Essence - Transitional', null],
  [
    'st398',
    'ST 398, Digital Video Recording - 1/2-in Type D-14 Component Format - 525/60 and 625/50',
    null,
  ],
  [
    'st399',
    'ST 399, Digital Television Recording - 1/2-in Type D-15 High-Definition Compressed Video Data Format',
    null,
  ],
  ['st400', 'ST 400, SMPTE Labels Structure', null],
  ['st401', 'ST 401, Extended Content ControlInformation (ExCCI) Data Packet', null],
  [
    'st402',
    'ST 402, Television - A Data Reduction Method for the MPEG-2 Video Recording Data Set',
    null,
  ],
  [
    'st405',
    'ST 405, Material Exchange Format (MXF) - Elements and Individual Data Items for the MXF Generic Container System Scheme 1',
    null,
  ],
  ['st407', 'ST 407, Material Exchange Format (MXF) - Operational Patterns 3a and 3b', null],
  ['st408', 'ST 408, Material Exchange Format (MXF) - Operational Patterns 1c, 2c and 3c', null],
  ['st409', 'ST 409, Digital Television Recording - 12.65-mm Type D-16 Format', null],
  ['st410', 'ST 410, Material Exchange Format — Generic Stream Partition', null],
  [
    'st411',
    'ST 411, Motion-Picture Film - Cinematography - Spectral Response of Photographic Audio Reproducers for Analog Dye Sound Tracks on 35-mm Film',
    null,
  ],
  [
    'st417',
    'ST 417, Motion-Picture Film (65-mm) - Camera Aperture Image and Usage, 15/70 Format',
    null,
  ],
  [
    'st418',
    'ST 418, Motion-Picture Film (65-mm) - Camera Aperture Image and Usage, 8/70 Format',
    null,
  ],
  ['st419', 'ST 419, Motion-Picture Film (70-mm) - Projectable Image Area, 15/70 Format', null],
  ['st420', 'ST 420, Motion-Picture Film (70-mm) - Projectable Image Area, 8/70 Format', null],
  ['st421', 'ST 421, VC-1 Compressed Video Bitstream Format and Decoding Process', null],
  [
    'st422',
    'ST 422, Material Exchange Format — Mapping JPEG 2000 Codestreams into the MXF Generic Container',
    null,
  ],
  ['st424', 'ST 424, 3 Gb/s Signal/Data Serial Interface', null],
  ['425', '425, Bit-Serial Interfaces at 3 Gb/s', null],
  ['ov425-0', 'OV 425-0, Roadmap for the 425 Document Suite', '425'],
  [
    'st425-1',
    'ST 425-1, Source Image Format and Ancillary Data Mapping for the 3 Gb/s Serial Interface',
    '425',
  ],
  [
    'st425-2',
    'ST 425-2, Source Image Format and Ancillary Data Mapping for Stereoscopic Image Formats on a Single-Link 3 Gb/s Serial Interface',
    '425',
  ],
  [
    'st425-3',
    'ST 425-3, Image Format and Ancillary Data Mapping for the Dual Link 3 Gb/s Serial Interface',
    '425',
  ],
  [
    'st425-4',
    'ST 425-4, Dual 3 Gb/s Serial Digital Interface for Stereoscopic Image Transport',
    '425',
  ],
  [
    'st425-5',
    'ST 425-5, Image Format and Ancillary Data Mapping for the Quad Link 3 Gb/s Serial Interface',
    '425',
  ],
  [
    'st425-6',
    'ST 425-6, Quad 3 Gb/s Serial Digital Interface for Stereoscopic Image Transport',
    '425',
  ],
  ['st427', 'ST 427, Link Encryption for 1.5 Gb/s Serial Digital Interface', null],
  ['428', '428, D-Cinema Distribution Master', null],
  ['st428-1', 'ST 428-1, Image Characteristics', '428'],
  ['st428-2', 'ST 428-2, Audio Characteristics', '428'],
  [
    'st428-3',
    'ST 428-3, D-Cinema Distribution Master Audio Channel Mapping and Channel Labeling',
    '428',
  ],
  [
    'rp428-4',
    'RP 428-4, D-Cinema Distribution Master —Audio File Format and Delivery Constraints',
    '428',
  ],
  ['rp428-5', 'RP 428-5, Mapping of Images into Constrained Tag Image File', '428'],
  ['rp428-6', 'RP 428-6, D-Cinema Distribution Master —Digital Leader', '428'],
  ['st428-7', 'ST 428-7, Subtitle', '428'],
  ['st428-9', 'ST 428-9, Serial Digital Interface Signal Formatting', '428'],
  [
    'st428-10',
    'ST 428-10, D-Cinema Distribution Master —Closed Caption and Closed Subtitle',
    '428',
  ],
  ['st428-11', 'ST 428-11, Additional Frame Rates for D-Cinema', '428'],
  [
    'st428-12',
    'ST 428-12, D-Cinema Distribution Master Common Audio Channels and Soundfield Groups',
    '428',
  ],
  [
    'st428-19',
    'ST 428-19, D-Cinema Distribution Master —Additional Frame RatesLevel AFR2 and Level AFR4 —Serial Digital Interface Signal Formatting',
    '428',
  ],
  ['st428-21', 'ST 428-21, Archive Frame Rates for D-Cinema', '428'],
  ['rp428-22', 'RP 428-22, Minimal Timed Text XML Requirements', '428'],
  [
    'eg428-23',
    'EG 428-23, D-Cinema Distribution Master — Mastering Guideline for Japanese Timed Text',
    '428',
  ],
  ['st428-24', 'ST 428-24, Packed Image', '428'],
  ['429', '429, D-Cinema Packaging', null],
  ['st429-2', 'ST 429-2, DCP Operational Constraints', '429'],
  ['st429-3', 'ST 429-3, Sound and Picture Track File', '429'],
  ['st429-4', 'ST 429-4, MXF JPEG 2000 Application', '429'],
  ['st429-5', 'ST 429-5, Timed Text Track File', '429'],
  ['st429-6', 'ST 429-6, MXF Track File Essence Encryption', '429'],
  ['st429-7', 'ST 429-7, Composition Playlist', '429'],
  ['st429-8', 'ST 429-8, D-Cinema Packaging —Packing List', '429'],
  ['st429-9', 'ST 429-9, Asset Mapping and File Segmentation', '429'],
  ['st429-10', 'ST 429-10, Stereoscopic Picture Track File', '429'],
  ['st429-12', 'ST 429-12, Caption and Closed Subtitle', '429'],
  [
    'st429-13',
    'ST 429-13, D-Cinema Packaging —DCP Operational Constraints for Additional Frame Rates',
    '429',
  ],
  ['st429-14', 'ST 429-14, Aux Data Track File', '429'],
  ['st429-16', 'ST 429-16, Additional Composition Metadata and Guidelines', '429'],
  ['st429-17', 'ST 429-17, XML Constraints', '429'],
  ['st429-18', 'ST 429-18, Immersive Audio Track File', '429'],
  ['st429-19', 'ST 429-19, DCP Operational Constraints for Immersive Audio', '429'],
  ['st429-20', 'ST 429-20, MXF Constraints', '429'],
  ['430', '430, D-Cinema Operations', null],
  ['st430-1', 'ST 430-1, Key Delivery Message', '430'],
  ['st430-2', 'ST 430-2, Digital Certificate', '430'],
  ['st430-3', 'ST 430-3, Generic Extra-Theater Message Format', '430'],
  ['st430-4', 'ST 430-4, Log Record Format Specification', '430'],
  ['st430-5', 'ST 430-5, Security Log Event Class and Constraints', '430'],
  ['st430-6', 'ST 430-6, Auditorium Security Messages for Intra-Theater Communications', '430'],
  ['st430-7', 'ST 430-7, Facility List Message', '430'],
  ['st430-9', 'ST 430-9, Key Delivery Bundle', '430'],
  ['st430-10', 'ST 430-10, Auxiliary Content Synchronization Protocol', '430'],
  ['st430-11', 'ST 430-11, Auxiliary Resource Presentation List', '430'],
  ['st430-12', 'ST 430-12, FSK Synchronization Signal', '430'],
  ['st430-14', 'ST 430-14, Digital Sync Signal and Aux Data Transfer Protocol', '430'],
  ['st430-15', 'ST 430-15, Facility List Message Exchange Protocol', '430'],
  ['st430-16', 'ST 430-16, Extended Facility List Message', '430'],
  ['st430-17', 'ST 430-17, SMS-OMB Communications Protocol Specification', '430'],
  ['431', '431, D-Cinema Quality', null],
  ['st431-1', 'ST 431-1, Screen Luminance Level, Chromaticity and Uniformity', '431'],
  ['rp431-2', 'RP 431-2, Reference Projector and Environment', '431'],
  ['432', '432, D-Cinema Signal Processing', null],
  ['eg432-1', 'EG 432-1, Color Processing for D-Cinema', '432'],
  [
    'eg432-2',
    'EG 432-2, D-Cinema Low Frequency Effects (LFE) Channel Audio Characteristics',
    '432',
  ],
  ['st433', 'ST 433, D-Cinema - XML Data Types', null],
  [
    'st434',
    'ST 434, Material Exchange Format — XML Encoding for Metadata and File Structure Information',
    null,
  ],
  ['435', '435, 10 Gb/s Serial Signal/Data Interface', null],
  ['ov435-0', 'OV 435-0, Roadmap', '435'],
  ['st435-1', 'ST 435-1, Part 1: Basic Stream Derivation', '435'],
  ['st435-2', 'ST 435-2, Basic Stream Data Mapping', '435'],
  ['st435-3', 'ST 435-3, Part 3: 10.6921 Gb/s Optical Fiber Interface', '435'],
  ['436', '436, Mapping of VI and ANC Data in MXF', null],
  ['st436-1', 'ST 436-1, MXF Mappings for VI Lines and Ancillary Data Packets', '436'],
  ['st436', 'ST 436, MXF Mappings for VBI Lines and Ancillary Data Packets', null],
  ['2001', '2001, XML Representation of SMPTE Registered Data', null],
  ['st2001-1', 'ST 2001-1, Mapping Rules', '2001'],
  ['st2001-2', 'ST 2001-2, AAF and MXF Data', '2001'],
  [
    'rp2002',
    'RP 2002, Content Specification on Solid State Media Card for DV/DV-Based Essence',
    null,
  ],
  ['st2003', 'ST 2003, Types Dictionary Structure', null],
  ['rp2005', 'RP 2005, Requirements for Equipment Compatibility with Non-PCM AES3 Streams', null],
  ['rp2006', 'RP 2006, Solid State Media (SSM) Card Specification', null],
  ['rp2007', 'RP 2007, Closed-Caption CDP and "Grand Alliance" Serial Interfaces for DTV', null],
  [
    'rp2008',
    'RP 2008, Material Exchange Format - Mapping AVC Streams into the MXF Generic Container',
    null,
  ],
  ['st2010', 'ST 2010, Vertical Ancillary Data Mapping of ANSI/SCTE 104 Messages', null],
  ['2016', '2016, Active Format Description', null],
  ['st2016-1', 'ST 2016-1, Format for Active Format Description and Bar Data', '2016'],
  ['st2016-2', 'ST 2016-2, Format for Pan-Scan Information', '2016'],
  [
    'st2016-3',
    'ST 2016-3, Vertical Ancillary Data Mapping of Active Format Description and Bar Data',
    '2016',
  ],
  ['st2016-4', 'ST 2016-4, Vertical Ancillary Data Mapping of Pan-Scan Information', '2016'],
  [
    'st2016-5',
    'ST 2016-5, KLV Coding for Active FormatDescription, Bar Data andPan-Scan Information',
    '2016',
  ],
  ['2019', '2019, VC-3 Video Compression', null],
  ['st2019-1', 'ST 2019-1, VC-3 Picture Compression and Data Stream Format', '2019'],
  ['rp2019-2', 'RP 2019-2, VC-3 Decoder and Bitstream Conformance', '2019'],
  ['st2019-3', 'ST 2019-3, VC-3 Type Data Stream Mapping Over SDTI', '2019'],
  ['st2019-4', 'ST 2019-4, Mapping VC-3 Coding Units into the MXF Generic Container', '2019'],
  ['2020', '2020, Audio Metadata', null],
  [
    'st2020-1',
    'ST 2020-1, Format of Audio Metadata and Description of the Asynchronous Serial Bitstream Transport',
    '2020',
  ],
  ['st2020-2', 'ST 2020-2, Method A', '2020'],
  ['st2020-3', 'ST 2020-3, Method B', '2020'],
  ['2021', '2021, Broadcast Exchange Format (BXF)', null],
  ['ov2021-0', 'OV 2021-0, Roadmap for the 2021 Document Suite', '2021'],
  ['rp2021-1', 'RP 2021-1, Requirements and Informative Notes', '2021'],
  ['st2021-1', 'ST 2021-1, Requirements and Informative Notes', '2021'],
  ['st2021-2', 'ST 2021-2, Broadcast Exchange Format (BXF) -Protocol', '2021'],
  ['eg2021-3', 'EG 2021-3, SMPTE Engineering Guideline BXF Use Cases', '2021'],
  ['eg2021-4', 'EG 2021-4, Broadcast Exchange Format (BXF) Schema Documentation', '2021'],
  ['st2021-4', 'ST 2021-4, Broadcast Exchange Format (BXF) Schema Documentation', '2021'],
  [
    'rp2021-5',
    'RP 2021-5, Using Ad-ID and EIDR as Alternate Identifiers in SMPTE BXF and ATSC PMCP',
    '2021',
  ],
  ['rp2021-6', 'RP 2021-6, BXF SDK Documentation', '2021'],
  ['rp2021-9', 'RP 2021-9, Implementing Broadcast Exchange Format (BXF)', '2021'],
  ['st2021', 'ST 2021, Broadcast Exchange Format (BXF)', null],
  ['2022', '2022, MPEG-2 Streams on IP Networks', null],
  [
    'st2022-1',
    'ST 2022-1, Forward Error Correction forReal-Time Video/AudioTransport Over IP Networks',
    '2022',
  ],
  [
    'st2022-2',
    'ST 2022-2, Unidirectional Transport of Constant Bit Rate MPEG-2 Transport Streams on IP Networks',
    '2022',
  ],
  [
    'st2022-3',
    'ST 2022-3, Unidirectional Transport of Variable Bit Rate MPEG-2 Transport Streams on IP Networks',
    '2022',
  ],
  [
    'st2022-4',
    'ST 2022-4, Unidirectional Transport ofNon-Piecewise Constant Variable Bit Rate MPEG-2 Streams on IP Networks',
    '2022',
  ],
  [
    'st2022-5',
    'ST 2022-5, Forward Error Correction for Transport of High Bit Rate Media Signals over IP Networks (HBRMT)',
    '2022',
  ],
  [
    'st2022-6',
    'ST 2022-6, Transport of High Bit Rate Media Signals over IP Networks (HBRMT)',
    '2022',
  ],
  ['st2022-7', 'ST 2022-7, Seamless Protection Switching of RTP Datagrams', '2022'],
  [
    'st2022-8',
    'ST 2022-8, Professional Media Over Managed IP Networks: Timing of ST 2022-6 Streams in ST 2110-10 Systems',
    '2022',
  ],
  ['rp2025', 'RP 2025, VC-1 Bitstream Storage in the ISO Base Media File', null],
  ['rp2027', 'RP 2027, AVC Intra-Frame Coding Specification for SSM Card Applications', null],
  ['st2029', 'ST 2029, Uniform Resource Names for SMPTE Resources', null],
  ['st2031', 'ST 2031, Carriage of DVB/SCTE VBI Data in VANC', null],
  ['2032', '2032, Media Dispatch Protocol (MDP)', null],
  ['st2032-1', 'ST 2032-1, Protocol Specification', '2032'],
  ['st2032-2', 'ST 2032-2, MDP/XML/HTTP Mapping Specification', '2032'],
  ['st2032-3', 'ST 2032-3, Basic Target Pull Profile Specification', '2032'],
  ['eg2032-4', 'EG 2032-4, Engineering Guideline (Informative)', '2032'],
  ['2034', '2034, Archive eXchange Format (AXF)', null],
  ['st2034-1', 'ST 2034-1, Part 1: Structure & Semantics', '2034'],
  ['st2035', 'ST 2035, Audio Channel Assignments for Digital Television Recorders (DTRs)', null],
  ['2036', '2036, Ultra High Definition Television', null],
  ['ov2036-0', 'OV 2036-0, Ultra High Definition Television', '2036'],
  ['st2036-1', 'ST 2036-1, Image Parameter Values for Program Production', '2036'],
  [
    'st2036-2',
    'ST 2036-2, Audio Characteristics and Audio Channel Mapping for Program Production',
    '2036',
  ],
  [
    'st2036-3',
    'ST 2036-3, Mapping into Single-link or Multi-link 10 Gb/s Serial Signal/Data Interface',
    '2036',
  ],
  [
    'st2036-4',
    'ST 2036-4, Multi-link 10 Gb/s Signal/Data Interface Using 12-Bit Width Container',
    '2036',
  ],
  ['st2037', 'ST 2037, Mapping VC-1 into the MXF Generic Container', null],
  ['st2038', 'ST 2038, Carriage of Ancillary Data Packets in an MPEG-2 Transport Stream', null],
  ['eg2039', 'EG 2039, Inspection and Cleaning Processes for the 304M Hybrid Connector', null],
  ['2041', '2041, Compressed Audio Formats in AES3', null],
  [
    'st2041-1',
    'ST 2041-1, Format for Non-PCM Audioin AES3 —MPEG Layer I, II, and III Audio',
    '2041',
  ],
  ['st2041-2', 'ST 2041-2, MPEG-2 AAC and HE AAC Audio in ADTS', '2041'],
  [
    'st2041-3',
    'ST 2041-3, MPEG-4 AAC and HE AAC Compressed Digital Audio in ADTS and LATM / LOAS Wrappers',
    '2041',
  ],
  ['2042', '2042, VC-2 Compression', null],
  ['st2042-1', 'ST 2042-1, VC-2 Video Compression', '2042'],
  ['st2042-2', 'ST 2042-2, VC-2 Level Definitions', '2042'],
  ['rp2042-3', 'RP 2042-3, VC-2 Conformance Specification', '2042'],
  ['st2042-4', 'ST 2042-4, Mapping a VC-2 Stream into the MXF Generic Container', '2042'],
  ['st2045', 'ST 2045, Register Interchange Format', null],
  ['2046', '2046, Safe Areas for Television', null],
  [
    'st2046-1',
    'ST 2046-1, Specifications for Safe Action and Safe Title Areasfor Television',
    '2046',
  ],
  ['rp2046-2', 'RP 2046-2, Safe Areas for Protection of Alternate Aspect Ratios', '2046'],
  ['eg2046-3', 'EG 2046-3, Safe Areas for Television', '2046'],
  ['2047', '2047, Carriage of VC-2 Compressed Video', null],
  [
    'rp2047-1',
    'RP 2047-1, VC-2 Mezzanine Level Compression of 1080P High Definition Video Sources',
    '2047',
  ],
  ['st2047-2', 'ST 2047-2, Carriage of VC-2 CompressedVideo over HD-SDI', '2047'],
  [
    'rp2047-3',
    'RP 2047-3, VC-2 Level 65 Compression of High Definition Video Sources for Use with a Standard Definition Infrastructure',
    '2047',
  ],
  ['st2047-4', 'ST 2047-4, Carriage of Level 65 VC-2 Compressed VideoOver the SDTV SDI', '2047'],
  [
    'rp2047-5',
    'RP 2047-5, VC-2 Level 66 Compression of Ultra-High Definition Video Sources for Use with a High Definition Infrastructure',
    '2047',
  ],
  ['2048', '2048, Digital Cinematography Product Image Format FS/709', null],
  ['ov2048-0', 'OV 2048-0, Roadmap for the 2048 Document Suite', '2048'],
  [
    'st2048-1',
    'ST 2048-1, 2048 × 1080 and 4096 × 2160 Digital Cinematography Production Image Formats FS/709',
    '2048',
  ],
  [
    'st2048-2',
    'ST 2048-2, 2048 × 1080 Digital Cinematography Production Image FS/709 Formatting for Serial Digital Interface',
    '2048',
  ],
  ['st2048-3', 'ST 2048-3, Mapping into Multi-link 10 Gb/s Serial Signal/Data Interface', '2048'],
  ['st2049', 'ST 2049, Low Latency Streaming MXF OP 1a', null],
  [
    '2050',
    '2050, 4:2:2 / 4:2:0 Format Conversion Minimizing Color Difference Signal Degradation in Concatenated Operations',
    null,
  ],
  ['rp2050-1', 'RP 2050-1, Filtering', '2050'],
  ['eg2050-2', 'EG 2050-2, Application', '2050'],
  [
    'st2051',
    'ST 2051, Two-Frame Marker for 48(/1.001)-Hz, 50-Hz, and 60(/1.001)-Hz Progressive Digital Video Signals on 1.5 Gb/s and 3 Gb/s Interfaces',
    null,
  ],
  ['2052', '2052, Timed Text Format (SMPTE-TT)', null],
  ['ov2052-0', 'OV 2052-0, Roadmap for the 2052 Document Suite', '2052'],
  ['st2052-1', 'ST 2052-1, Timed Text Format (SMPTE-TT)', '2052'],
  ['rp2052-10', 'RP 2052-10, Conversion from CEA-608 Data to SMPTE-TT', '2052'],
  ['rp2052-11', 'RP 2052-11, Conversion from CEA-708 Caption Data to SMPTE-TT', '2052'],
  [
    'st2053',
    'ST 2053, Media Package for Storage, Distribution and Playback of Multimedia File Sets and Internet Resources',
    null,
  ],
  [
    'rp2054',
    'RP 2054, Method of Measurement of Perceived Loudness of Short Duration Motion Picture Audio Material',
    null,
  ],
  ['st2056', 'ST 2056, MPEG TS Packets Carried in VANC', null],
  ['rp2057', 'RP 2057, Text-Based MetadataCarriage in MXF', null],
  ['2058', '2058, VC-4 Video Compression', null],
  [
    'st2058-1',
    'ST 2058-1, VC-4 Layered Video Extension Bitstream Format and Decoding Process',
    '2058',
  ],
  ['rp2058-2', 'RP 2058-2, VC-4 Decoder and Bitstream Conformance', '2058'],
  ['rp2058-3', 'RP 2058-3, VC-4 Bitstream Transport Encodings', '2058'],
  ['rp2058-4', 'RP 2058-4, VC-4 Bitstream Storage in the ISO Base Media File Format', '2058'],
  ['2059', '2059, Precision Time Protocol in Professional Broadcast Applications', null],
  [
    'st2059-1',
    'ST 2059-1, Generation and Alignment of Interface Signals to the SMPTE Epoch',
    '2059',
  ],
  [
    'st2059-2',
    'ST 2059-2, SMPTE Profile for Use of IEEE-1588 Precision Time Protocol in Professional Broadcast Applications',
    '2059',
  ],
  [
    'eg2059-10',
    'EG 2059-10, Introduction to the New Synchronization System (SMPTE ST 2059)',
    '2059',
  ],
  [
    'rp2059-15',
    'RP 2059-15, YANG Data Model for ST 2059-2 PTP Device Monitoring in Professional Broadcast Applications',
    '2059',
  ],
  ['eg2061', 'EG 2061, Stereoscopic Distribution Master - Glossary', null],
  ['st2063', 'ST 2063, Stereoscopic 3D Full Resolution Contribution Link Based on MPEG-2 TS', null],
  ['2064', '2064, Audio to Video Synchronization Measurement', null],
  ['st2064-1', 'ST 2064-1, Fingerprint Generation', '2064'],
  ['st2064-2', 'ST 2064-2, Fingerprint Transport', '2064'],
  ['2065', '2065, Academy', null],
  ['st2065-1', 'ST 2065-1, Academy Color Encoding Specification (ACES)', '2065'],
  [
    'st2065-2',
    'ST 2065-2, Spectral Responsivities, Reference Measurement Device and Spectral Calculation',
    '2065',
  ],
  ['st2065-3', 'ST 2065-3, Encoding Academy Printing Density (APD) Values', '2065'],
  ['st2065-4', 'ST 2065-4, ACES Image Container File Layout', '2065'],
  ['st2065-5', 'ST 2065-5, Mapping ACES Image Sequences into the MXF Generic Container', '2065'],
  ['st2066', 'ST 2066, Disparity Map Representation for Stereoscopic 3D', null],
  ['2067', '2067, Interoperable Master Format (IMF)', null],
  ['ov2067-0', 'OV 2067-0, Interoperable Master Format', '2067'],
  ['st2067-2', 'ST 2067-2, Core Constraints', '2067'],
  ['st2067-3', 'ST 2067-3, Composition Playlist', '2067'],
  ['st2067-5', 'ST 2067-5, Essence Component', '2067'],
  ['st2067-8', 'ST 2067-8, Common Audio Labels', '2067'],
  ['st2067-9', 'ST 2067-9, Sidecar Composition Map', '2067'],
  ['st2067-20', 'ST 2067-20, Application #2', '2067'],
  ['st2067-21', 'ST 2067-21, Application #2E', '2067'],
  ['st2067-30', 'ST 2067-30, Application #3', '2067'],
  ['st2067-40', 'ST 2067-40, Application #4 Cinema Mezzanine', '2067'],
  ['st2067-50', 'ST 2067-50, Application #5 ACES', '2067'],
  ['st2067-60', 'ST 2067-60, Application #6 UHDTV Program Workflow (AVC)', '2067'],
  ['st2067-70', 'ST 2067-70, Application SMPTE ST 2019-1 (VC-3)', '2067'],
  ['st2067-71', 'ST 2067-71, Application SMPTE ST 2117-1 (VC-6)', '2067'],
  ['st2067-100', 'ST 2067-100, Output Profile List', '2067'],
  ['st2067-101', 'ST 2067-101, Common Image Definitions and Macros', '2067'],
  ['st2067-102', 'ST 2067-102, Common Image Pixel Color Schemes', '2067'],
  ['st2067-103', 'ST 2067-103, Common Audio Definition and Macros', '2067'],
  [
    'st2067-200',
    'ST 2067-200, Dynamic Metadata for Color Volume Transform (DMCVT) Plug-in',
    '2067',
  ],
  ['st2067-201', 'ST 2067-201, Immersive Audio Bitstream Level 0 Plug-in', '2067'],
  ['st2067-202', 'ST 2067-202, Isochronous Stream of XML Documents (ISXD) Plug-in', '2067'],
  ['st2067-203', 'ST 2067-203, Audio with Frame-based S-ADM Metadata Plug-in', '2067'],
  ['st2067-204', 'ST 2067-204, Audio with ADM Metadata Plug-in', '2067'],
  ['st2068', 'ST 2068, Stereoscopic 3D Frame Compatible Packing and Signaling for HDTV', null],
  ['eg2069', 'EG 2069, Optical SDI Networks', null],
  ['2070', '2070, Stereoscopic 3D in MXF', null],
  ['st2070-1', 'ST 2070-1, Common Provisions', '2070'],
  ['st2070-2', 'ST 2070-2, OP1a Mapping', '2070'],
  ['st2070-3', 'ST 2070-3, OP-Atom or Single Track OP-1a Mapping', '2070'],
  ['2071', '2071, Media Device Control Framework (MDCF)', null],
  ['st2071-1', 'ST 2071-1, Media Device Control Framework (MDCF)', '2071'],
  ['st2071-2', 'ST 2071-2, Media Device Control Protocol (MDCP)', '2071'],
  ['st2071-3', 'ST 2071-3, Media Device Control Discovery (MDCD)', '2071'],
  [
    'rp2072',
    'RP 2072, Emphasis and Preferred Sampling Rate for AES/EBU Digital Audio in Television',
    null,
  ],
  ['2073', '2073, VC-5 Compression', null],
  ['ov2073-0', 'OV 2073-0, Document Suite Overview', '2073'],
  ['st2073-1', 'ST 2073-1, Part 1: Elementary Bitstream', '2073'],
  ['rp2073-2', 'RP 2073-2, VC-5 Video Essence Part 2. Conformance Specification', '2073'],
  ['st2073-3', 'ST 2073-3, Part 3: Image Formats', '2073'],
  ['st2073-4', 'ST 2073-4, Part 4: Subsampled Color Difference Components', '2073'],
  ['st2073-5', 'ST 2073-5, Part 5: Layers', '2073'],
  ['st2073-6', 'ST 2073-6, Part 6: Sections', '2073'],
  ['st2073-7', 'ST 2073-7, VC-5 Video Essence Part 7. Metadata', '2073'],
  ['st2073-10', 'ST 2073-10, Mapping VC-5 Video Essence into the MXF Generic Container', '2073'],
  ['eg2074', 'EG 2074, SMPTE Metadata Naming Guidelines', null],
  ['st2075', 'ST 2075, Mapping EBU TECH 3264 (STL) into the MXF Generic Stream Container', null],
  ['2076', '2076, Stereoscopic (S3D) or Multi-Camera Array', null],
  [
    'rp2076-1',
    'RP 2076-1, Production Timing and Synchronization for Stereoscopic (S3D) or Multi-Camera Array',
    '2076',
  ],
  [
    'eg2076-2',
    'EG 2076-2, Image Identification, Alignment, Transport and System Guidance for Stereoscopic (S3D) or Multi-Camera Array',
    '2076',
  ],
  ['rp2077', 'RP 2077, Full-Range Image Mapping', null],
  [
    'rp2079',
    'RP 2079, Digital Object Identifier (DOI) Name and Entertainment ID Registry (EIDR) Identifier Representations',
    null,
  ],
  ['2080', '2080, Luminance Level and Chromaticity', null],
  ['st2080-1', 'ST 2080-1, Reference White Luminance Level and Chromaticity for HDTV', '2080'],
  [
    'rp2080-2',
    'RP 2080-2, Measurement and Calibration Procedure for HDTV Display Luminance Levels and Chromaticity',
    '2080',
  ],
  ['st2080-3', 'ST 2080-3, Reference Viewing Environment for Evaluation of HDTV Images', '2080'],
  ['2081', '2081, 6G-SDI', null],
  [
    'ov2081-0',
    'OV 2081-0, 6G-SDI Bit-Serial Interfaces Roadmap for the SMPTE ST 2081 Document Suite',
    '2081',
  ],
  ['st2081-1', 'ST 2081-1, Electrical', '2081'],
  [
    'st2081-10',
    'ST 2081-10, 2160-line and 1080-line Source Image and Ancillary Data Mapping for 6G-SDI',
    '2081',
  ],
  [
    'st2081-11',
    'ST 2081-11, 2160-line and 1080-line Source Image and Ancillary Data Mapping for Dual-link 6G-SDI',
    '2081',
  ],
  [
    'st2081-12',
    'ST 2081-12, 4320-line and 2160-line Source Image and Ancillary Data Mapping for Quad-link 6G-SDI',
    '2081',
  ],
  [
    'st2081-30',
    'ST 2081-30, Transport of Multiple 3Gb/s or 1.5Gb/s signals on a 6G-SDI link',
    '2081',
  ],
  ['2082', '2082, 12G-SDI', null],
  ['ov2082-0', 'OV 2082-0, Overview for the SMPTE ST 2082 Document Suite', '2082'],
  ['st2082-1', 'ST 2082-1, Electrical', '2082'],
  [
    'st2082-10',
    'ST 2082-10, 2160-line and 1080-line Source Image and Ancillary Data Mapping for 12G-SDI',
    '2082',
  ],
  [
    'st2082-11',
    'ST 2082-11, 4320-line and 2160-line Source Image and Ancillary Data Mapping for Dual-link 12G-SDI',
    '2082',
  ],
  [
    'st2082-12',
    'ST 2082-12, 4320-line and 2160-line Source Image and Ancillary Data Mapping for Quad-link 12G-SDI',
    '2082',
  ],
  [
    'st2082-30',
    'ST 2082-30, Transport of Multiple 6Gb/s, 3Gb/s or 1.5Gb/s signals on a 12G-SDI link',
    '2082',
  ],
  [
    'st2084',
    'ST 2084, High Dynamic Range Electro-Optical Transfer Function of Mastering Reference Displays',
    null,
  ],
  [
    'st2085',
    'ST 2085, Y′D′ZD′X Color-Difference Computations for High Dynamic Range X′Y′Z′ Signals',
    null,
  ],
  [
    'st2086',
    'ST 2086, Mastering Display Color Volume Metadata Supporting High Luminance and Wide Color Gamut Images',
    null,
  ],
  ['st2087', 'ST 2087, Depth Map Representation', null],
  ['st2088', 'ST 2088, Essence Element Key Register Structure', null],
  ['rp2089', 'RP 2089, Carriage of EIDR Identifiers in MXF Files', null],
  ['2091', '2091, Ruggedized Fiber-Optic Connectors', null],
  ['st2091-1', 'ST 2091-1, Ruggedized Fiber-Optic Connectors for HDTV and UHDTV SDI', '2091'],
  ['rp2091-2', 'RP 2091-2, Mapping of SMPTE ST 2036-4 Data', '2091'],
  ['2092', '2092, Advertising Digital Identifier (Ad-ID)', null],
  ['rp2092-1', 'RP 2092-1, Advertising Digital Identifier (Ad-ID®) Representations', '2092'],
  ['rp2093', 'RP 2093, Television Lighting Consistency Index (TLCI)', null],
  ['2094', '2094, Dynamic Metadata for Color Volume Transform', null],
  ['ov2094-0', 'OV 2094-0, Overview for the SMPTE ST 2094 Document Suite', '2094'],
  ['st2094-1', 'ST 2094-1, Core Components', '2094'],
  ['st2094-2', 'ST 2094-2, KLV Encoding and MXF Mapping', '2094'],
  ['st2094-10', 'ST 2094-10, Application #1', '2094'],
  ['st2094-20', 'ST 2094-20, Application #2', '2094'],
  ['st2094-30', 'ST 2094-30, Application #3', '2094'],
  ['st2094-40', 'ST 2094-40, Application #4', '2094'],
  ['st2094-50', 'ST 2094-50, Application #5', '2094'],
  ['st2094-60', 'ST 2094-60, Application #6', '2094'],
  ['2095', '2095, Cinema Sound', null],
  ['st2095-1', 'ST 2095-1, Calibration Reference Wideband Digital Pink Noise Signal', '2095'],
  ['2096', '2096, Cinema Sound Calibration', null],
  ['rp2096-1', 'RP 2096-1, Cinema Sound System Baseline Setup and Calibration', '2096'],
  ['rp2096-2', 'RP 2096-2, Cinema Sound System Maintenance Calibration', '2096'],
  ['2098', '2098, Immersive Audio', null],
  ['st2098-1', 'ST 2098-1, Immersive Audio Metadata', '2098'],
  ['st2098-2', 'ST 2098-2, Immersive Audio Bitstream Specification', '2098'],
  [
    'eg2098-3',
    'EG 2098-3, Immersive Audio Renderer Expectations and Testing Recommendations',
    '2098',
  ],
  ['st2098-5', 'ST 2098-5, D-Cinema Immersive Audio Channels and Soundfield Groups', '2098'],
  ['2100', '2100, Haptic-Tactile Essence for Broadcast Production Applications', null],
  [
    'st2100-1',
    'ST 2100-1, Definition and Representation of Haptic-Tactile Essence for Broadcast Production Applications',
    '2100',
  ],
  ['st2101', 'ST 2101, Format for Non-PCM Audio and Data in AES3 - AC-4 Data Type', null],
  ['st2102', 'ST 2102, SMPTE Core Metadata', null],
  ['st2106', 'ST 2106, Format for Non-PCM Audio in AES3 - Type17 Compressed Audio', null],
  ['2108', '2108, HDR and WCG Metadata', null],
  [
    'st2108-1',
    'ST 2108-1, HDR/WCG Metadata Packing and Signaling in the Vertical Ancillary Data Space',
    '2108',
  ],
  [
    'st2108-2',
    'ST 2108-2, Vertical Ancillary Data Mapping of KLV Formatted HDR/WCG Metadata',
    '2108',
  ],
  ['st2109', 'ST 2109, Format for Non-PCM Audio and Data in AES3 — Audio Metadata', null],
  ['2110', '2110, Professional Media Over Managed IP Networks', null],
  ['ov2110-0', 'OV 2110-0, Roadmap for the 2110 Document Suite', '2110'],
  ['st2110-10', 'ST 2110-10, System Timing and Definitions', '2110'],
  ['st2110-20', 'ST 2110-20, Uncompressed Active Video', '2110'],
  ['st2110-21', 'ST 2110-21, Traffic Shaping and Delivery Timing for Video', '2110'],
  ['st2110-22', 'ST 2110-22, Constant Bit-Rate Compressed Video', '2110'],
  [
    'rp2110-23',
    'RP 2110-23, Single Video Essence Transport over Multiple ST 2110-20 Streams',
    '2110',
  ],
  [
    'rp2110-24',
    'RP 2110-24, Special Considerations for Standard Definition Video Using SMPTE ST 2110-20',
    '2110',
  ],
  ['rp2110-25', 'RP 2110-25, Measurement Practices', '2110'],
  ['st2110-30', 'ST 2110-30, PCM Digital Audio', '2110'],
  ['st2110-31', 'ST 2110-31, AES3 Transparent Transport', '2110'],
  ['st2110-40', 'ST 2110-40, SMPTE ST 291-1 Ancillary Data', '2110'],
  ['st2110-41', 'ST 2110-41, Fast Metadata Framework', '2110'],
  ['st2110-43', 'ST 2110-43, Timed Text Markup Language for Captions and Subtitles', '2110'],
  ['2111', '2111, SDI Roadmap', null],
  ['eg2111-1', 'EG 2111-1, SD-SDI and HD-SDI Standards Roadmap', '2111'],
  ['eg2111-2', 'EG 2111-2, 3/6/12 & 24 Gbit/s SDI Standards Roadmap', '2111'],
  ['eg2111-3', 'EG 2111-3, 10G-SDI Standards Roadmap', '2111'],
  ['2112', '2112, Open Binding of Content Identifiers (OBID)', null],
  ['ov2112-0', 'OV 2112-0, Roadmap for the 2112 Document Suite', '2112'],
  ['rp2112-1', 'RP 2112-1, Audience Measurement Using OBID and OBID-TLC', '2112'],
  ['eg2112-2', 'EG 2112-2, Audience Measurement Ecosystem', '2112'],
  ['st2112-10', 'ST 2112-10, Open Binding of Content Identifiers (OBID)', '2112'],
  ['rp2112-11', 'RP 2112-11, Conformance Test Materials', '2112'],
  [
    'st2112-20',
    'ST 2112-20, Open Binding of Distribution Channel IDs and Timestamps (OBID-TLC)',
    '2112',
  ],
  ['rp2112-21', 'RP 2112-21, Conformance Test Materials', '2112'],
  ['st2113', 'ST 2113, Colorimetry of P3 Color Spaces', null],
  ['st2114', 'ST 2114, Unique Digital Media Identifier (C4 ID)', null],
  [
    'st2115',
    'ST 2115, Free Scale Gamut and Free Scale Log Characteristics of Camera Signals',
    null,
  ],
  [
    'st2116',
    'ST 2116, Format for Non-PCM Audio and Data in AES3 — Carriage of Metadata of Serial ADM (Audio Definition Model)',
    null,
  ],
  ['2117', '2117, VC-6 Video compression', null],
  ['st2117-1', 'ST 2117-1, Part 1. Elementary Bitstream', '2117'],
  ['st2117-10', 'ST 2117-10, Mapping VC-6 into the MXF Generic Container', '2117'],
  ['2120', '2120, Extensible Time Label', null],
  ['st2120-1', 'ST 2120-1, Structure', '2120'],
  ['st2122', 'ST 2122, Spectral Similarity Index (SSI)', null],
  ['st2123', 'ST 2123, SMPTE Metadata Registers', null],
  [
    'st2124',
    'ST 2124, Material Exchange Format — Mapping JPEG XS Codestreams into the MXF Generic Container',
    null,
  ],
  ['st2126', 'ST 2126, Microservice Status Reporting and Logging', null],
  ['2127', '2127, Metadata-Guided Audio (MGA)', null],
  [
    'st2127-1',
    'ST 2127-1, Mapping Metadata-Guided Audio (MGA) signals into the MXF Constrained Generic Container',
    '2127',
  ],
  ['st2127-2', 'ST 2127-2, Mapping MGA Audio Metadata to ST 2110-41', '2127'],
  [
    'st2127-10',
    'ST 2127-10, Mapping Metadata-Guided Audio (MGA) signals with S-ADM Metadata into the MXF Constrained Generic Container',
    '2127',
  ],
  [
    'st2128',
    'ST 2128, BT.2100 RGB Conversion to IPT-PQ-C2 Color Space for High Dynamic Range and Wide Color Gamut Images',
    null,
  ],
  ['rp2129', 'RP 2129, Inter-Entity Trust Boundary', null],
  [
    'st2131',
    'ST 2131, Mapping Audio Definition Model (ADM) and other audio metadata RIFF Chunks to MXF',
    null,
  ],
  ['st2134', 'ST 2134, MXF Descriptive Metadata Scheme for Compatible Time Labels (DMS-TLC)', null],
  ['2136', '2136, Common LUT Format', null],
  ['st2136-1', 'ST 2136-1, Core Specification', '2136'],
  ['st2139', 'ST 2139, Signal Sync Alternate Mode', null],
] satisfies readonly CatalogRow[];
